force-app/main/default/objects/CCXR_User__c/CCXR_User__c.object-meta.xml
<CustomObject>
    <label>CCXR User</label>
    <nameField>
        <displayFormat>USR-{0000}</displayFormat>
        <label>CCXR User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CCXR_User__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_User__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <label>UserName</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AddUpdateCCXUser.cls
public class AddUpdateCCXUser {
        public static void addCCXUser(List<User> newusers)
        {
           list<CCXR_User__c> addnewusers=new list<CCXR_User__c>();
            For(User u:newusers)
            {
               CCXR_User__c newuser=new CCXR_User__c();
                newuser.UserName__c=u.UserName;
                addnewusers.add(newuser);
            }
            insert addnewusers;
        }
        public static void updateCCXUser(List<User> oldusers,List<User> updatedusers)
        {
            List<Id> userIds=new List<Id>();
             For(User u:oldusers)
             {
                userIds.add(u.Id); 
             }
           
          list<CCXR_User__c> updatenewusers=[select id,Username__c,UserId__c,Password__c From CCXR_User__c
                                             Where UserId__c in:userIds];
          list<CCXR_User__c> updatenewusers2=new list<CCXR_User__c>();
            For(User u:updatedusers)
            {
                For(CCXR_User__c nu:updatenewusers)
            {
               CCXR_User__c updateuser=new CCXR_User__c();
                if(u.Id==nu.UserId__c && u.UserName !=nu.UserName__c)
                {
                nu.UserName__c=u.UserName;
                updatenewusers2.add(nu);
            }
            }
            update updatenewusers2;  
        }
        }
    }