force-app/main/default/objects/CCXR_User__c/CCXR_User__c.object-meta.xml
<CustomObject>
    <label>CCXR User</label>
    <nameField>
        <displayFormat>USR-{0000}</displayFormat>
        <label>CCXR User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_User__c/fields/Employee_Type__c.field-meta.xml
<CustomField>
    <fullName>Employee_Type__c</fullName>
    <label>Employee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chef</fullName>
            </value>
            <value>
                <fullName>Waiter</fullName>
            </value>
            <value>
                <fullName>Front Desk Manager</fullName>
            </value>
            <value>
                <fullName>Restaurant Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CCXR_User__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <label>UserName</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UserLoginPageController.cls
public class UserLoginPageController {
    @AuraEnabled
    public static String checkDetails(String username, String password) { 
        List<CCXR_User__c> userList = [ SELECT Id, UserName__c, Password__c,Employee_Type__c FROM CCXR_User__c
          								  WHERE UserName__c = :username
          								  LIMIT 1];
        
        if(userList.isEmpty()) {
            return 'User does not exist'; 
        } else {
            CCXR_User__c user = userList[0];
            if(user.Password__c == password) {
                return 'Login successful!';
            } else {
                return 'Invalid password, please try again';
            }
        }
        
    }
   
    @AuraEnabled(cacheable=true)
    public static CCXR_User__c getDetails(string username) { 
        CCXR_User__c userList = [ SELECT Id,Employee_Type__c,UserName__c, Password__c FROM CCXR_User__c
          								where UserName__c=:username];
        return userList;
    }
}