force-app/main/default/objects/CCXR_Items__c/CCXR_Items__c.object-meta.xml
<CustomObject>
    <label>CCXR_Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>CCXR_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Name__c</fullName>
    <label>CCXR_Item Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Prep_Time__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Prep_Time__c</fullName>
    <label>CCXR_Item_Prep_Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 Min</fullName>
                <default>true</default>
                <label>10 Min</label>
            </value>
            <value>
                <fullName>15 Min</fullName>
            </value>
            <value>
                <fullName>20 Min</fullName>
            </value>
            <value>
                <fullName>25 Min</fullName>
            </value>
            <value>
                <fullName>40 Min</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Status__c</fullName>
    <label>CCXR_Item_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Out of Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Price__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Price__c</fullName>
    <label>CCXR_Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Serves__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Serves__c</fullName>
    <label>CCXR_Serves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Special_Item__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Special_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CCXR_Special Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/Item_Image__c.field-meta.xml
<CustomField>
    <fullName>Item_Image__c</fullName>
    <formula>IMAGE( Item_Image_Link__c , &quot; &quot; , 150, 200)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/Item_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Item_Image_Link__c</fullName>
    <label>Item Image Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetSpecialItems.cls
/*
* Author : Jyothi Nandaluri
 * Creation Date : 14/03/2023, 10:29 pm	
 * Last Modification : 03/04/2023, 12:01 pm
 * Purpose : To retrieve the special items data in the items object. 
*/
public with sharing class GetSpecialItems {
    @AuraEnabled(cacheable=true)
    //To retreive the special items from items object.
    public static List<CCXR_Items__c> getTodaySpecialMenu()
    {
        List<CCXR_Items__c> menuItems = [SELECT CCXR_Item_Name__c, CCXR_Item_Status__c, 
                                        CCXR_Special_Item__c,Item_Image__c,Item_Image_Link__c,
                                        CCXR_Serves__c,CCXR_Price__c,CCXR_Item_Prep_Time__c
                                        FROM CCXR_Items__c 
                                        WHERE CCXR_Item_Status__c = 'Available' AND CCXR_Special_Item__c=true];
        return menuItems;
    }
}