force-app/main/default/objects/CCXR_Items__c/CCXR_Items__c.object-meta.xml
<CustomObject>
    <label>CCXR_Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>CCXR_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Category__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Category__c</fullName>
    <label>CCXR_Item_Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Vegetarian</fullName>
            </value>
            <value>
                <fullName>Non-Vegetarian</fullName>
            </value>
            <value>
                <fullName>Beverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Name__c</fullName>
    <label>CCXR_Item Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Status__c</fullName>
    <label>CCXR_Item_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Out of Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_SubCategory__c</fullName>
    <label>CCXR_Item_SubCategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CCXR_Item_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Starters</fullName>
            </value>
            <value>
                <fullName>Soups</fullName>
            </value>
            <value>
                <fullName>Rice</fullName>
            </value>
            <value>
                <fullName>Curries</fullName>
            </value>
            <value>
                <fullName>Roti</fullName>
            </value>
            <value>
                <fullName>Desserts</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Milkshakes</fullName>
            </value>
            <value>
                <fullName>Ice Creams</fullName>
            </value>
            <value>
                <fullName>Sweets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetItemsTest.cls
@isTest
private class GetItemsTest {
	@isTest
    private static void testGetMenuItems(){
        //Create test data
        CCXR_Items__c item=new CCXR_Items__c(CCXR_Item_Name__c='Test',CCXR_Item_Category__c='Vegetarian',
                                    CCXR_Item_SubCategory__c='Soups',
            	                    CCXR_Item_Status__c='Available');
        insert item;
        //Call the method being tested
        GetItems.getMenuItems('Vegetarian','Soups');
        //Verify the expected results
        system.assertEquals('Test', item.CCXR_Item_Name__c);
        system.assertNotEquals('item', item.CCXR_Item_Name__c);
        
    }
}