force-app/main/default/objects/CCXR_Customer__c/CCXR_Customer__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>CCXR_Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/No_Of_Persons__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Persons__c</fullName>
    <label>No Of Persons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/CCXR_Customer_Table_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer Table Status</label>
    <nameField>
        <displayFormat>CTSN-{0000}</displayFormat>
        <label>CCXR_CustomerTableStatusNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customer Table Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Button_1__c.field-meta.xml
<CustomField>
    <fullName>Button_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Button 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer</label>
    <referenceTo>CCXR_Customer__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Table</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Table__c.CCXR_Table_Status__c</field>
            <operation>equals</operation>
            <value>Vacant, Reserved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Table__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Customer_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Table_Status__c</fullName>
    <label>Customer Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Time_of_reservation__c.field-meta.xml
<CustomField>
    <fullName>Time_of_reservation__c</fullName>
    <label>Time of reservation</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Timeofvisit__c.field-meta.xml
<CustomField>
    <fullName>Timeofvisit__c</fullName>
    <label>Timeofvisit</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Token_Number__c.field-meta.xml
<CustomField>
    <fullName>Token_Number__c</fullName>
    <label>Token Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/waittime__c.field-meta.xml
<CustomField>
    <fullName>waittime__c</fullName>
    <formula>IF((NOW() - Timeofvisit__c) * 24 * 60 &lt; 60,
    TEXT(FLOOR((NOW() - Timeofvisit__c) * 24 * 60)) &amp; &quot; mins&quot;,
    TEXT(FLOOR((NOW() - Timeofvisit__c) * 24)) &amp; &quot; hrs &quot; &amp; TEXT(MOD(FLOOR((NOW() - Timeofvisit__c) * 24 * 60), 60)) &amp; &quot; mins&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>waittime</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/waittimeinmins__c.field-meta.xml
<CustomField>
    <fullName>waittimeinmins__c</fullName>
    <formula>FLOOR((NOW() - Timeofvisit__c) * 24 * 60)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>waittimeinmins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Capacity__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Capacity__c</fullName>
    <label>CCXR_Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table_Status__c</fullName>
    <label>CCXR_Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
                <default>true</default>
                <label>Vacant</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/Time_Of_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Time_Of_Reservation__c</fullName>
    <label>Time Of Reservation</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CustomerTableController.cls
//Author:R Yaswanth Reddy
//Date Creation :12/03/2023
//Date Modified: 15/03/2023
//Purpose :list of customer table records in waiting status,
//This Class contains 5 methods
public with sharing class CustomerTableController
{
    /*
* @AuraEnabled method to retrieve a list of customer table records with waiting status
* @return List<CCXR_Customer_Table_Status__c> - list of customer table records
*/
    @AuraEnabled(cacheable = true)
    public static List<CCXR_Customer_Table_Status__c> getAllTable(){
        // Retrieve customer table records with waiting status
        List<CCXR_Customer_Table_Status__c> accList =[select Name,waittime__c,waittimeinmins__c,Button_1__c,Customer_Table_Status__c,Token_Number__c,
                                   CCXR_Customer__r.CCXR_Name__c,CCXR_Table__r.Name,CCXR_Customer__r.No_Of_Persons__c,
                                     Timeofvisit__c from  
                                     CCXR_Customer_Table_Status__c where Customer_Table_Status__c='Waiting' or Customer_Table_Status__c='Reserved' ORDER BY waittime__c desc ];
        // Return the list of customer table records
        return accList;
    }
    //Purpose of the Class:when a customer is assigned to a table
    @AuraEnabled
    public static List<CCXR_Customer_Table_Status__c> setstatus(Id recid,Id tid,integer ran)
    {
        /*
* @AuraEnabled method to update the status of a customer table record when assigned to a table
* @recid - Id of the customer table record
* @tid - Id of the table assigned to the customer
* @ran - integer value of the token number assigned to the customer
* @return List<CCXR_Customer_Table_Status__c> - list of updated customer table records
*/
        List<CCXR_Customer_Table_Status__c> up= new List<CCXR_Customer_Table_Status__c> ();
        List<CCXR_Customer_Table_Status__c> accList1 =[select Customer_Table_Status__c,CCXR_Table__c,Token_Number__c from  
                                                       CCXR_Customer_Table_Status__c where id=:recid];
        for (CCXR_Customer_Table_Status__c acc:acclist1) {
            acc.Customer_Table_Status__c='Occupied';
            acc.CCXR_Table__c=tid;
            acc.Token_Number__c=ran;
            up.add(acc);
        }
      update up;
        // Update the customer table records
        RETURN up;
        // Return the updated customer table records     
    }
    /*
@AuraEnabled method to update the status of table record, customer is assigned to a table
@param recid - Id of the table record
@return List<CCXR_Table__c> - list of updated table records
*/
    @AuraEnabled
    public static List<CCXR_Table__c> tsetstatus(Id recid){
        List<CCXR_Table__c> up= new List<CCXR_Table__c> ();
        // Retrieve the table record that needs to be updated
        List<CCXR_Table__c> accList1 =[select CCXR_Table_Status__c from  CCXR_Table__c where id=:recid];
        for (CCXR_Table__c acc:acclist1) {
            acc.CCXR_Table_Status__c='Occupied';
            
            up.add(acc);
        }
        // Update the table records
        update up;
        // Return the updated table records
        RETURN up;
    }
    /*
@AuraEnabled method to retrieve a list of table records with Vacant or Reserved status
@return List<CCXR_Table__c> - list of table records
*/
    @AuraEnabled(cacheable=true)
    public static List<CCXR_Table__c> getTableRecords() {
        // Retrieve table records with Vacant or Reserved status
        return [SELECT Id,Name,CCXR_Capacity__c FROM CCXR_Table__c where  CCXR_Table_Status__c in ('Vacant', 'Reserved') ];
    }
    /*
@AuraEnabled method  retrieve a list of customer table statuses with Occupied
@return List<CCXR_Customer_Table_Status__c> - list of table records
*/
   @AuraEnabled
    public static List<CCXR_Customer_Table_Status__c> getCustomerTableStatus(){
        List<CCXR_Customer_Table_Status__c> accList =[select Name,Customer_Table_Status__c,Token_Number__c,
                         CCXR_Customer__r.CCXR_Name__c,CCXR_Table__r.Name,CCXR_Customer__r.No_Of_Persons__c from  
                                        CCXR_Customer_Table_Status__c where Customer_Table_Status__c='Occupied'];
        return accList;
    }
   
    @AuraEnabled
    public static CCXR_Customer_Table_Status__c getCustomerReservedData(id csn,id tid,boolean but2)
    {
        CCXR_Customer_Table_Status__c rcst =[select id,Customer_Table_Status__c,Button_1__c,Token_Number__c,CCXR_Table__c
                                             from  CCXR_Customer_Table_Status__c 
                                             where id=:csn];
        
        rcst.Customer_Table_Status__c='Reserved';
        rcst.CCXR_Table__c=tid;
      rcst.Button_1__c=but2;
        update rcst;
       
        return rcst;
        
    }
    @AuraEnabled
    public static List<CCXR_Table__c> getCustomerReservedData1(Id recid){
        List<CCXR_Table__c> up= new List<CCXR_Table__c> ();
        // Retrieve the table record that needs to be updated
        List<CCXR_Table__c> accList1 =[select CCXR_Table_Status__c from  CCXR_Table__c where id=:recid];
        for (CCXR_Table__c acc:acclist1) {
            acc.CCXR_Table_Status__c='Reserved';
            acc.Time_Of_Reservation__c=datetime.now();
            up.add(acc);
        }
        // Update the table records
        update up;
        // Return the updated table records
        RETURN up;
        
    }   
}