force-app/main/default/objects/CCXR_Customer__c/CCXR_Customer__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>CCXR_Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Phone_Number__c</fullName>
    <label>CCXR_Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/No_Of_Persons__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Persons__c</fullName>
    <label>No Of Persons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/CCXR_Customer_Table_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer Table Status</label>
    <nameField>
        <displayFormat>CTSN-{0000}</displayFormat>
        <label>CCXR_CustomerTableStatusNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customer Table Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer</label>
    <referenceTo>CCXR_Customer__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Customer_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Table_Status__c</fullName>
    <label>Customer Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Visit_History__c/fields/CCXR_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer_Id__c</fullName>
    <label>CCXR_Customer Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Visit_History__c/fields/CCXR_Customer_Visited_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer_Visited_Date_and_Time__c</fullName>
    <label>CCXR_Customer Visited Date and Time</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Visit_History__c/fields/CCXR_Number_Of_Persons__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Number_Of_Persons__c</fullName>
    <label>CCXR_Number Of Persons</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExistingCustomerTest.cls
/* Author Name : Satya Umesh
Date Of Creation : 12/04/2023
Date last Modified : 13/04/2023
Purpose of Test Class : To Test the Data that we are Feteching in Class ExistingCustomerController
*/


@istest
private class ExistingCustomerTest
{
	@isTest
    static void testGetPhoneNum() 
    {
        // Create test data
        CCXR_Customer__c customer = new CCXR_Customer__c(CCXR_Phone_Number__c = '1234567890', No_Of_Persons__c = 2);
        insert customer;
        
        // Call the controller method
        List<CCXR_Customer__c> result = ExistingCustomerController.getPhoneNum('1234567890');
        
        // Verify the results
        System.assertEquals(1, result.size(), 'Expected 1 record to be returned');
        CCXR_Customer__c actualCustomer = result[0];
        System.assertEquals(customer.Id, actualCustomer.Id, 'Incorrect record returned');
        System.assertEquals(customer.CCXR_Phone_Number__c, actualCustomer.CCXR_Phone_Number__c, 'Incorrect phone number');
        System.assertEquals(customer.No_Of_Persons__c, actualCustomer.No_Of_Persons__c, 'Incorrect number of persons');
    }
    @isTest
    static void testCreateCST() {
        // Create a test customer record
        CCXR_Customer__c customer = new CCXR_Customer__c(CCXR_Phone_Number__c = '123-456-7890', No_Of_Persons__c = 2);
        insert customer;
        
        // Call the controller method
        ExistingCustomerController.createCST(customer.Id);
        
        // Verify the results
        List<CCXR_Customer_Table_Status__c> tableStatuses = [SELECT Id, Customer_Table_Status__c FROM CCXR_Customer_Table_Status__c WHERE CCXR_Customer__c = :customer.Id];
         System.assertEquals('Waiting', tableStatuses[0].Customer_Table_Status__c, 'Incorrect customer table status');
        
        List<Customer_Visit_History__c> visitHistories = [SELECT Id, CCXR_Customer_Id__c, CCXR_Number_Of_Persons__c, CCXR_Customer_Visited_Date_and_Time__c FROM Customer_Visit_History__c WHERE CCXR_Customer_Id__c = :customer.Name];
        Customer_Visit_History__c visitHistory = visitHistories[0];
        
        System.assertEquals(customer.Name, visitHistory.CCXR_Customer_Id__c, 'Incorrect customer Id');
        System.assertEquals(customer.No_Of_Persons__c, visitHistory.CCXR_Number_Of_Persons__c, 'Incorrect number of persons');
    }
}