force-app/main/default/objects/CCXR_Customer__c/CCXR_Customer__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>CCXR_Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order__c/CCXR_Order__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>CCXR_Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Grand_Total__c</fullName>
    <label>CCXR_Grand Total</label>
    <summarizedField>CCXR_Order_Line_Item__c.CCXR_New_Total__c</summarizedField>
    <summaryForeignKey>CCXR_Order_Line_Item__c.CCXR_Order_ID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Net_Total__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Net_Total__c</fullName>
    <formula>(CCXR_Grand_Total__c + (CCXR_Grand_Total__c * CCXR_Tax__c )) - (CCXR_Grand_Total__c *  CCXR_OrderDiscount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Net Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_Status__c</fullName>
    <label>CCXR_Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Progress</fullName>
                <default>true</default>
                <label>Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_OrderDiscount__c.field-meta.xml
<CustomField>
    <fullName>CCXR_OrderDiscount__c</fullName>
    <formula>IF( 
AND(CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_No_of_Visits__c &gt;1,CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_No_of_Visits__c&lt;=5), 0.05, 
IF( CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_No_of_Visits__c &gt;5,0.10,0)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_OrderDiscount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Tax__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Tax__c</fullName>
    <defaultValue>0.08</defaultValue>
    <label>CCXR_Tax</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/CCXR_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000}</displayFormat>
        <label>CCXR_OrderLineItem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Name__c</fullName>
    <formula>CCXR_Item_ID__r.CCXR_Item_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Order_ID__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_ID__c</fullName>
    <label>CCXR_Order ID</label>
    <referenceTo>CCXR_Order__c</referenceTo>
    <relationshipLabel>CCXR_Order Line Items</relationshipLabel>
    <relationshipName>CCXR_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_OrderLineItem_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_OrderLineItem_Status__c</fullName>
    <label>CCXR_OrderLineItem_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Picked-up</fullName>
            </value>
            <value>
                <fullName>Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Price__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Price__c</fullName>
    <formula>CCXR_Item_ID__r.CCXR_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Total__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Total__c</fullName>
    <formula>CCXR_Quantity__c  *  CCXR_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/getorderstatusescontroller.cls
//Author Name:-K.jagadeeswar Reddy
 //  Date Of Creation:- 24-03-2023
  // Date last modified :-28-03-2023

  // Purpose :- To get the data of order and orderlineitems Which order status are completed 
  //                         and orderlineitemstatus are served
public class getorderstatusescontroller {
    
    @AuraEnabled(cacheable=true)
    // passing order id as parameter
    public static list<CCXR_Order_Line_Item__c> orderstatuses(Id orderid)
    {
        integer i=0;
        integer j=0;
        // Storing orderlineitems list in n1 variable
        list<CCXR_Order_Line_Item__c> n1=new  list<CCXR_Order_Line_Item__c> ();
        // fetching the data of order status completed 
        list<CCXR_Order_Line_Item__c>                            
            
            orderst=[select CCXR_OrderLineItem_Status__c,CCXR_Order_ID__r.CCXR_Order_Status__c,
                     CCXR_Order_ID__r.CCXR_Customer__c, CCXR_Order_ID__r.CCXR_Table__c,CCXR_Order_ID__r.Name,
                     CCXR_Order_ID__r.CCXR_Grand_Total__c,CCXR_Order_ID__r.CCXR_Tax__c,CCXR_Order_ID__r.CCXR_OrderDiscount__c,
                     CCXR_Order_ID__r.CCXR_Net_Total__c,
                     Name,CCXR_Item_Name__c,CCXR_Quantity__c,CCXR_Price__c,CCXR_Total__c
                     from CCXR_Order_Line_Item__c
                     where  
                     CCXR_Order_ID__r.CCXR_Order_Status__c ='Completed' AND CCXR_Order_ID__C=:orderid
                    ];
        // Itertating orderdata with order lineitems and fetching the data of orderlineitem status served
        for(CCXR_Order_Line_Item__c oli:orderst)
        {
            i++;
            if(oli.CCXR_OrderLineItem_Status__c=='Served')
            {
                j++;
            }
            
            if(i==j)
            {   
                n1.add(oli);
            }
        }
        return n1;
    }
}