force-app/main/default/objects/CCXR_Customer__c/CCXR_Customer__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>CCXR_Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Phone_Number__c</fullName>
    <label>CCXR_Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/No_Of_Persons__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Persons__c</fullName>
    <label>No Of Persons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/CCXR_Customer_Table_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer Table Status</label>
    <nameField>
        <displayFormat>CTSN-{0000}</displayFormat>
        <label>CCXR_CustomerTableStatusNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customer Table Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer</label>
    <referenceTo>CCXR_Customer__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Customer_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Table_Status__c</fullName>
    <label>Customer Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Timeofvisit__c.field-meta.xml
<CustomField>
    <fullName>Timeofvisit__c</fullName>
    <label>Timeofvisit</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Customer_Visit_History__c/fields/CCXR_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer_Id__c</fullName>
    <label>CCXR_Customer Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Visit_History__c/fields/CCXR_Customer_Visited_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer_Visited_Date_and_Time__c</fullName>
    <label>CCXR_Customer Visited Date and Time</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Visit_History__c/fields/CCXR_Number_Of_Persons__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Number_Of_Persons__c</fullName>
    <label>CCXR_Number Of Persons</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExistingCustomerController.cls
/* Author Name : Satya Umesh
	Date Of Creation : 11/04/2023
	Date last Modified : 13/04/2023
	Purpose of Class : For the Existing Customers we need to get the data via phone number .
*/

public with sharing class ExistingCustomerController
{
    // To get the Data From Customers with selected phone no And Pass it to "Alreadyvisitedcustomer.js"  In lwc

    @AuraEnabled (cacheable=true)
    public static List<CCXR_Customer__c> getPhoneNum(string ph)
    {
        List<CCXR_Customer__c> cts= [SELECT Id,CCXR_Phone_Number__c,No_Of_Persons__c FROM CCXR_Customer__c where CCXR_Phone_Number__c=:ph];  
        
        system.debug(cts);
        
        return cts;
    }
    
    //passing cid to here from js
    
    @AuraEnabled 
    public static void createCST(id cid) 
    {
        
        CCXR_Customer__c css=[SELECT Id,Name,CCXR_Phone_Number__c,No_Of_Persons__c FROM CCXR_Customer__c where id=:cid];
        
        CCXR_Customer_Table_Status__c csst=new CCXR_Customer_Table_Status__c();
        csst.CCXR_Customer__c=cid;
        csst.Customer_Table_Status__c='Waiting';
        csst.Timeofvisit__c=datetime.now();
        insert csst;
        
        CCXR_Customer_Table_Status__c acc = [SELECT CreatedDate FROM CCXR_Customer_Table_Status__c where id=:csst.id];
        String createDateStr = acc.CreatedDate.format('yyyy-MM-dd HH:mm:ss');
        System.debug('Create date as string: ' + createDateStr);
        
        Customer_Visit_History__c cvh=new Customer_Visit_History__c();
        cvh.CCXR_Customer_Id__c=css.Name;
        cvh.CCXR_Number_Of_Persons__c=css.No_Of_Persons__c;
        cvh.CCXR_Customer_Visited_Date_and_Time__c=createDateStr;
        
        insert cvh;
    }
    
}