force-app/main/default/objects/CCXR_Customer__c/CCXR_Customer__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>CCXR_Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Phone_Number__c</fullName>
    <label>CCXR_Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/No_Of_Persons__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Persons__c</fullName>
    <label>No Of Persons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/CCXR_Customer_Table_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer Table Status</label>
    <nameField>
        <displayFormat>CTSN-{0000}</displayFormat>
        <label>CCXR_CustomerTableStatusNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customer Table Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer</label>
    <referenceTo>CCXR_Customer__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Table</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Table__c.CCXR_Table_Status__c</field>
            <operation>equals</operation>
            <value>Vacant, Reserved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Table__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Customer_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Table_Status__c</fullName>
    <label>Customer Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Time_of_reservation__c.field-meta.xml
<CustomField>
    <fullName>Time_of_reservation__c</fullName>
    <label>Time of reservation</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Token_Number__c.field-meta.xml
<CustomField>
    <fullName>Token_Number__c</fullName>
    <label>Token Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/CCXR_Restaurant_Employee__c.object-meta.xml
<CustomObject>
    <label>CCXR_Restaurant Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>CCXR_Restaurant Emp Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Restaurant Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Aadhar_Number__c</fullName>
    <label>CCXR_Aadhar Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Phone__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Phone__c</fullName>
    <label>CCXR_Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Type_of_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Type_of_Employee__c</fullName>
    <label>CCXR_Type_of_Employee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Restaurant Manager</fullName>
            </value>
            <value>
                <fullName>Front Desk Manager</fullName>
            </value>
            <value>
                <fullName>Chef</fullName>
            </value>
            <value>
                <fullName>Waiter</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Capacity__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Capacity__c</fullName>
    <label>CCXR_Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Restaurant_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Restaurant_Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Restaurant_Employee__c.CCXR_Type_of_Employee__c</field>
            <operation>equals</operation>
            <value>Waiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Tables</relationshipLabel>
    <relationshipName>CCXR_Tables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table_Status__c</fullName>
    <label>CCXR_Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
                <default>true</default>
                <label>Vacant</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/Time_Of_Reservation__c.field-meta.xml
<CustomField>
    <fullName>Time_Of_Reservation__c</fullName>
    <label>Time Of Reservation</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/customertableControllerTest.cls
@isTest
private class customertableControllerTest {
    @isTest static void testGetAllAccountsas() {
        // Create test data
        
        CCXR_Restaurant_Employee__c	 rsc=new CCXR_Restaurant_Employee__c();
        rsc.CCXR_Aadhar_Number__c='5328 6358 1129';
        rsc.CCXR_Phone__c='7207601245';
        rsc.CCXR_Type_of_Employee__c='Waiter';
        insert rsc;
        
        CCXR_Customer_Table_Status__c testRecord = new CCXR_Customer_Table_Status__c(Customer_Table_Status__c = 'Waiting');
        insert testRecord;
        
        // Call the method being tested
        List<CCXR_Customer_Table_Status__c> result = customertableController.getAllTable();
        
        // Verify the expected result
        System.assertEquals(1, result.size());
        
    }
    
    @isTest static void testSetstatus() {
        // Create test data
        
        CCXR_Restaurant_Employee__c	 rsc=new CCXR_Restaurant_Employee__c();
        rsc.CCXR_Aadhar_Number__c='5328 6358 1129';
        rsc.CCXR_Phone__c='7207601245';
        rsc.CCXR_Type_of_Employee__c='Waiter';
        insert rsc;
        
        CCXR_Table__c testTable = new CCXR_Table__c(CCXR_Table_Status__c = 'Vacant',CCXR_Restaurant_Employee__c=rsc.id);
        insert testTable;
        
        CCXR_Customer_Table_Status__c testRecord = new CCXR_Customer_Table_Status__c(Customer_Table_Status__c = 'Waiting', Token_Number__c = 0);
        insert testRecord;
        
        // Call the method being tested
        List<CCXR_Customer_Table_Status__c> result = customertableController.setstatus(testRecord.Id, testTable.Id, 123);
        
        // Verify the expected result
        System.assertEquals(1, result.size());
        System.assertEquals('Occupied', result[0].Customer_Table_Status__c);
        
        System.assertEquals(123, result[0].Token_Number__c);
    }
    
    @isTest static void testTsetstatus() {
        // Create test data
        
        CCXR_Restaurant_Employee__c	 rsc=new CCXR_Restaurant_Employee__c();
        rsc.CCXR_Aadhar_Number__c='5328 6358 1129';
        rsc.CCXR_Phone__c='7207601245';
        rsc.CCXR_Type_of_Employee__c='Waiter';
        insert rsc;
        
        CCXR_Table__c testTable = new CCXR_Table__c(CCXR_Table_Status__c = 'Vacant',CCXR_Restaurant_Employee__c=rsc.id);
        insert testTable;
        
        // Call the method being tested
        List<CCXR_Table__c> result = customertableController.tsetstatus(testTable.Id);
        
        // Verify the expected result
        System.assertEquals(1, result.size());
        System.assertEquals('Occupied', result[0].CCXR_Table_Status__c);
    }
    
    @isTest static void testGetAccountNames() {
        // Create test data
        
        
        CCXR_Restaurant_Employee__c	 rsc=new CCXR_Restaurant_Employee__c();
        rsc.CCXR_Aadhar_Number__c='5328 6358 1129';
        rsc.CCXR_Phone__c='7207601245';
        rsc.CCXR_Type_of_Employee__c='Waiter';
        insert rsc;
        
        CCXR_Table__c testTable1 = new CCXR_Table__c(CCXr_Capacity__c = 2, CCXR_Table_Status__c = 'Vacant',CCXR_Restaurant_Employee__c=rsc.Id );
        CCXR_Table__c testTable2 = new CCXR_Table__c(CCXr_Capacity__c = 4, CCXR_Table_Status__c = 'Reserved', CCXR_Restaurant_Employee__c=rsc.id);
        insert new List<CCXR_Table__c> { testTable1, testTable2 };
            
            // Call the method being tested
            List<CCXR_Table__c> result = customertableController.getTableRecords();
        
        // Verify the expected result
        System.assertEquals(2, result.size());
        
    }
    
    @isTest static void testGetCustomerTableStatus() {
        // Create test data
        CCXR_Customer_Table_Status__c testRecord = new CCXR_Customer_Table_Status__c(Customer_Table_Status__c = 'Occupied');
        insert testRecord;
        
        // Call the method being tested
        List<CCXR_Customer_Table_Status__c> result = customertableController.getCustomerTableStatus();
    }
    @isTest 
    static void testGetCustomerReservedData() {
        // Create a test record for CCXR_Customer_Table_Status__c
        
        CCXR_Restaurant_Employee__c	 rsc=new CCXR_Restaurant_Employee__c();
        rsc.CCXR_Aadhar_Number__c='5328 6358 1129';
        rsc.CCXR_Phone__c='7207601245';
        rsc.CCXR_Type_of_Employee__c='Waiter';
        insert rsc;
        
        CCXR_Customer__c cust = new CCXR_Customer__c();
        cust.CCXR_Name__c='Test Customer';
        cust.No_Of_Persons__c=4;
        cust.CCXR_Phone_Number__c='6303279407';
        insert cust;
        
        CCXR_Table__c tb = new CCXR_Table__c();
        tb.CCXR_Capacity__c=6;
        tb.CCXR_Table_Status__c='Vacant';
        tb.CCXR_Restaurant_Employee__c=rsc.id;
        insert tb;
        
        CCXR_Customer_Table_Status__c testRecord = new CCXR_Customer_Table_Status__c(
            Customer_Table_Status__c = 'Occupied',
        	CCXR_Customer__c=cust.id,
            CCXR_Table__c=tb.id
        );
        insert testRecord;
        
         CCXR_Customer_Table_Status__c result = CustomerTableController.getCustomerReservedData(
            testRecord.Id, tb.id, 123, true
        );
    }
    
    @isTest 
    static void testGetCustomerReservedData1() {
        // Create a test record for CCXR_Table__c
        
        CCXR_Restaurant_Employee__c	 rsc=new CCXR_Restaurant_Employee__c();
        rsc.CCXR_Aadhar_Number__c='5328 6358 1129';
        rsc.CCXR_Phone__c='7207601245';
        rsc.CCXR_Type_of_Employee__c='Waiter';
        insert rsc;
        
        CCXR_Table__c testRecord = new CCXR_Table__c(
            CCXR_Table_Status__c = 'Vacant',
        	CCXR_Restaurant_Employee__c=rsc.Id
        );
        insert testRecord;

        // Call the method with the test record's ID
        List<CCXR_Table__c> result = CustomerTableController.getCustomerReservedData1(testRecord.Id);

        // Verify that the record was updated correctly
        System.assertEquals(1, result.size());
        System.assertEquals('Reserved', result[0].CCXR_Table_Status__c);
        System.assertNotEquals(null, result[0].Time_Of_Reservation__c);
    }
    
}