force-app/main/default/objects/CCXR_Customer__c/CCXR_Customer__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>CCXR_Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Phone_Number__c</fullName>
    <label>CCXR_Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/No_Of_Persons__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Persons__c</fullName>
    <label>No Of Persons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/CCXR_Customer_Table_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer Table Status</label>
    <nameField>
        <displayFormat>CTSN-{0000}</displayFormat>
        <label>CCXR_CustomerTableStatusNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customer Table Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer</label>
    <referenceTo>CCXR_Customer__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Table</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Table__c.CCXR_Table_Status__c</field>
            <operation>equals</operation>
            <value>Vacant, Reserved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Table__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Customer_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Table_Status__c</fullName>
    <label>Customer Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/CCXR_Order__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>CCXR_Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Customer_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer_Table_Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer Table Status</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Customer_Table_Status__c.Customer_Table_Status__c</field>
            <operation>equals</operation>
            <value>Occupied</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Customer_Table_Status__c</referenceTo>
    <relationshipLabel>CCXR_Orders</relationshipLabel>
    <relationshipName>CCXR_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_Status__c</fullName>
    <label>CCXR_Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Progress</fullName>
                <default>true</default>
                <label>Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Receipts__c/CCXR_Receipts__c.object-meta.xml
<CustomObject>
    <label>CCXR Receipts</label>
    <nameField>
        <displayFormat>RCP-{0000}</displayFormat>
        <label>CCXR Receipts ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Receipts__c/fields/Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Amount_Received__c</fullName>
    <formula>CCXR_Order__r.CCXR_Net_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCXR_Receipts__c/fields/CCXR_Order__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Order</label>
    <referenceTo>CCXR_Order__c</referenceTo>
    <relationshipLabel>CCXR Receipts</relationshipLabel>
    <relationshipName>CCXR_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Receipts__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <formula>DATEVALUE( CCXR_Order__r.CreatedDate )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Capacity__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Capacity__c</fullName>
    <label>CCXR_Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table_Status__c</fullName>
    <label>CCXR_Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
                <default>true</default>
                <label>Vacant</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReceiptsDataTest.cls
/* Author Name : Satya Umesh
Date Of Creation : 31/03/2023
Date last Modified : 03/04/2023
Purpose of Test Class : To Test the Data that we are Feteching in Class ReceiptsDataController
*/

@isTest
private class ReceiptsDataTest 
{
    // To test the data of ReceiptsData method from Controller class ReceiptsDataController
    
    @istest
    private static void testReceiptsData() 
    {
        
        CCXR_Order__c order = new CCXR_Order__c();
        order.CCXR_Customer_Table_Status__c='a0A2w00000iYpRuEAK';
        order.CCXR_Order_Status__c='Paid';
        insert order;
        
        CCXR_Receipts__c rcp=new CCXR_Receipts__c();
        rcp.CCXR_Order__c=order.Id;
        
        insert rcp;
        
        // Call the method being tested
        ReceiptsDataController.getReceiptList();
        list<CCXR_Receipts__c> rcplist=[SELECT  Name, CCXR_Order__c,Amount_Received__c,CCXR_Order__r.CCXR_Customer__c,
                                        CCXR_Order__r.CCXR_Table__c,Transaction_Date__c                
                                        FROM CCXR_Receipts__c where CCXR_Order__r.CCXR_Order_Status__c='Paid'];
        
        // Verify the expected result
        System.assertEquals(1,rcplist.size());
        System.assertEquals('Paid',order.CCXR_Order_Status__c);
    }
    
    
    // To test the data of setorderstatus method from Controller class ReceiptsDataController
    
    @istest
    private static void testOrderstatus() 
    {
         CCXR_Customer__c cust = new CCXR_Customer__c();
        cust.CCXR_Name__c='Test Customer';
        cust.No_Of_Persons__c=4;
        cust.CCXR_Phone_Number__c='6303279407';
        insert cust;
       
        CCXR_Table__c tbls = new CCXR_Table__c();
        tbls.CCXR_Capacity__c=6;
        tbls.CCXR_Table_Status__c='Vacant';
        insert tbls;
       
        CCXR_Customer_Table_Status__c cst=new CCXR_Customer_Table_Status__c();
        cst.CCXR_Customer__c=cust.id;
        cst.CCXR_Table__c=tbls.Id;
        cst.Customer_Table_Status__c='Occupied';
        insert cst;
        
        CCXR_Order__c order = new CCXR_Order__c();
        order.CCXR_Customer_Table_Status__c=cst.id;
        order.CCXR_Order_Status__c='Progress';
        insert order;
        
        CCXR_Order__c ordc=[select CCXR_Customer_Table_Status__r.CCXR_Table__r.CCXR_Table_Status__c,
                            CCXR_Order_Status__c,CCXR_Table__c from CCXR_Order__c where id=:order.id ];
        ordc.CCXR_Order_Status__c='Paid';
        update ordc;
        
        CCXR_Customer_Table_Status__c cts=[SELECT  CCXR_Table__c,CCXR_Table__r.CCXR_Table_Status__c 
                                           FROM CCXR_Customer_Table_Status__c where id=:ordc.CCXR_Customer_Table_Status__c];
        system.debug(cts.CCXR_Table__r.CCXR_Table_Status__c);
        
        CCXR_Table__c tb=[select CCXR_Table_Status__c from CCXR_Table__c where id=:cts.CCXR_Table__c];
        system.debug(tb.CCXR_Table_Status__c);
        tb.CCXR_Table_Status__c='Vacant';
        
        update tb;
        
        // Call the method being tested
        ReceiptsDataController.setorderstatus(order.Id);
        list<CCXR_Table__c> tbs=[select CCXR_Table_Status__c from CCXR_Table__c where id=:tb.id];
        
        // Verify the expected result
        System.assertEquals(1,tbs.size());
    }
}