force-app/main/default/objects/CCXR_Customer__c/CCXR_Customer__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>CCXR_Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Phone_Number__c</fullName>
    <label>CCXR_Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/CCXR_Customer_Table_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer Table Status</label>
    <nameField>
        <displayFormat>CTSN-{0000}</displayFormat>
        <label>CCXR_CustomerTableStatusNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customer Table Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer</label>
    <referenceTo>CCXR_Customer__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Table</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Table__c.CCXR_Table_Status__c</field>
            <operation>equals</operation>
            <value>Vacant, Reserved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Table__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Token_Number__c.field-meta.xml
<CustomField>
    <fullName>Token_Number__c</fullName>
    <label>Token Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/CCXR_Restaurant_Employee__c.object-meta.xml
<CustomObject>
    <label>CCXR_Restaurant Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>CCXR_Restaurant Emp Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Restaurant Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Aadhar_Number__c</fullName>
    <label>CCXR_Aadhar Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Type_of_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Type_of_Employee__c</fullName>
    <label>CCXR_Type_of_Employee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Restaurant Manager</fullName>
            </value>
            <value>
                <fullName>Front Desk Manager</fullName>
            </value>
            <value>
                <fullName>Chef</fullName>
            </value>
            <value>
                <fullName>Waiter</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Capacity__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Capacity__c</fullName>
    <label>CCXR_Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Restaurant_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Restaurant_Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Restaurant_Employee__c.CCXR_Type_of_Employee__c</field>
            <operation>equals</operation>
            <value>Waiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Tables</relationshipLabel>
    <relationshipName>CCXR_Tables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerTableStatusDataTest.cls
@isTest
private class CustomerTableStatusDataTest {

    @isTest
    static void testGetCustomerTableStatusData() {
        CCXR_Customer__c c1= new CCXR_Customer__c();
        c1.CCXR_Name__c='Sunil';
        c1.CCXR_Phone_Number__c='99898998';
        insert c1;
        CCXR_Restaurant_Employee__c r=new CCXR_Restaurant_Employee__c();
        r.CCXR_Name__c='Sunil';
        r.CCXR_Aadhar_Number__c='0000 0000 0000';
        r.CCXR_Type_of_Employee__c='Waiter';
        insert r;
        CCXR_Table__c t= new CCXR_Table__c();
        t.CCXR_Capacity__c=3;
        t.CCXR_Restaurant_Employee__c=r.id;
        insert t;
        // Create a new CCXR_Customer_Table_Status__c record
        CCXR_Customer_Table_Status__c cts = new CCXR_Customer_Table_Status__c(
            Token_Number__c = 123,
            CCXR_Customer__c = c1.id,
            CCXR_Table__c = t.id
        );
        insert cts;

        // Call the getCustomerTableStatusData method with the token value of 123
        CCXR_Customer_Table_Status__c result = CustomerTableStatusData.getCustomerTableStatusData(123);

        // Verify that the returned record matches the expected record
       
        System.assertEquals(cts.Token_Number__c, result.Token_Number__c);
    }
}