force-app/main/default/objects/CCXR_Customer__c/CCXR_Customer__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>CCXR_Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/CCXR_Customer_Table_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer Table Status</label>
    <nameField>
        <displayFormat>CTSN-{0000}</displayFormat>
        <label>CCXR_CustomerTableStatusNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customer Table Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer</label>
    <referenceTo>CCXR_Customer__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Table</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Table__c.CCXR_Table_Status__c</field>
            <operation>equals</operation>
            <value>Vacant, Reserved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Table__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Token_Number__c.field-meta.xml
<CustomField>
    <fullName>Token_Number__c</fullName>
    <label>Token Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomerTableStatusData.cls
public class CustomerTableStatusData {
	@AuraEnabled(cacheable=true)

    public static CCXR_Customer_Table_Status__c  getCustomerTableStatusData(integer token)
    {
      
        CCXR_Customer_Table_Status__c cts = [select  Id,Name,CCXR_Customer__r.Name,CCXR_Table__r.Name,
                                             Token_Number__c
                                             from CCXR_Customer_Table_Status__c 
                                             where Token_Number__c=:token];
        
        return cts;
    }
}