force-app/main/default/objects/CCXR_Customer__c/CCXR_Customer__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>CCXR_Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/CCXR_Customer_Table_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer Table Status</label>
    <nameField>
        <displayFormat>CTSN-{0000}</displayFormat>
        <label>CCXR_CustomerTableStatusNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customer Table Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer</label>
    <referenceTo>CCXR_Customer__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Table</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Table__c.CCXR_Table_Status__c</field>
            <operation>equals</operation>
            <value>Vacant, Reserved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Table__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/CCXR_Items__c.object-meta.xml
<CustomObject>
    <label>CCXR_Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>CCXR_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Category__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Category__c</fullName>
    <label>CCXR_Item_Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Vegetarian</fullName>
            </value>
            <value>
                <fullName>Non-Vegetarian</fullName>
            </value>
            <value>
                <fullName>Beverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Name__c</fullName>
    <label>CCXR_Item Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_SubCategory__c</fullName>
    <label>CCXR_Item_SubCategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CCXR_Item_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Starters</fullName>
            </value>
            <value>
                <fullName>Soups</fullName>
            </value>
            <value>
                <fullName>Rice</fullName>
            </value>
            <value>
                <fullName>Curries</fullName>
            </value>
            <value>
                <fullName>Roti</fullName>
            </value>
            <value>
                <fullName>Desserts</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Milkshakes</fullName>
            </value>
            <value>
                <fullName>Ice Creams</fullName>
            </value>
            <value>
                <fullName>Sweets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Price__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Price__c</fullName>
    <label>CCXR_Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/CCXR_Order__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>CCXR_Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Customer_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer_Table_Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer Table Status</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Customer_Table_Status__c.Customer_Table_Status__c</field>
            <operation>equals</operation>
            <value>Occupied</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Customer_Table_Status__c</referenceTo>
    <relationshipLabel>CCXR_Orders</relationshipLabel>
    <relationshipName>CCXR_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Grand_Total__c</fullName>
    <label>CCXR_Grand Total</label>
    <summarizedField>CCXR_Order_Line_Item__c.CCXR_New_Total__c</summarizedField>
    <summaryForeignKey>CCXR_Order_Line_Item__c.CCXR_Order_ID__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Net_Total__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Net_Total__c</fullName>
    <formula>(CCXR_Grand_Total__c + (CCXR_Grand_Total__c * CCXR_Tax__c )) - (CCXR_Grand_Total__c *  CCXR_OrderDiscount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Net Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_Status__c</fullName>
    <label>CCXR_Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Progress</fullName>
                <default>true</default>
                <label>Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_OrderDiscount__c.field-meta.xml
<CustomField>
    <fullName>CCXR_OrderDiscount__c</fullName>
    <formula>IF( 
AND(CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_No_of_Visits__c &gt;1,CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_No_of_Visits__c&lt;=5), 0.05, 
IF( CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_No_of_Visits__c &gt;5,0.10,0)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_OrderDiscount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Tax__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Tax__c</fullName>
    <defaultValue>0.08</defaultValue>
    <label>CCXR_Tax</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/CCXR_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000}</displayFormat>
        <label>CCXR_OrderLineItem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Item_Category__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Category__c</fullName>
    <label>CCXR_Item_Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vegetarian</fullName>
            </value>
            <value>
                <fullName>Non-Vegetarian</fullName>
            </value>
            <value>
                <fullName>Beverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Item_ID__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Item ID</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>CCXR_Items__c.CCXR_Item_Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.CCXR_Item_Category__c</valueField>
        </filterItems>
        <filterItems>
            <field>CCXR_Items__c.CCXR_Item_SubCategory__c</field>
            <operation>equals</operation>
            <valueField>$Source.CCXR_Item_SubCategory__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Items__c</referenceTo>
    <relationshipLabel>CCXR_Order Line Items</relationshipLabel>
    <relationshipName>CCXR_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Name__c</fullName>
    <formula>CCXR_Item_ID__r.CCXR_Item_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Item_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_SubCategory__c</fullName>
    <label>CCXR_Item_SubCategory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Starters</fullName>
            </value>
            <value>
                <fullName>Desserts</fullName>
            </value>
            <value>
                <fullName>Soups</fullName>
            </value>
            <value>
                <fullName>Rice</fullName>
            </value>
            <value>
                <fullName>Roti</fullName>
            </value>
            <value>
                <fullName>Curries</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Milkshakes</fullName>
            </value>
            <value>
                <fullName>Ice Creams</fullName>
            </value>
            <value>
                <fullName>Sweets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Order_ID__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_ID__c</fullName>
    <label>CCXR_Order ID</label>
    <referenceTo>CCXR_Order__c</referenceTo>
    <relationshipLabel>CCXR_Order Line Items</relationshipLabel>
    <relationshipName>CCXR_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_OrderLineItem_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_OrderLineItem_Status__c</fullName>
    <label>CCXR_OrderLineItem_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Picked-up</fullName>
            </value>
            <value>
                <fullName>Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Price__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Price__c</fullName>
    <formula>CCXR_Item_ID__r.CCXR_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Total__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Total__c</fullName>
    <formula>CCXR_Quantity__c  *  CCXR_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Order_CreationController.cls
public with sharing class Order_CreationController
{
    
    public static Id neworderid;
    @AuraEnabled()
    public static void  createOrderAndOrderLines(id csn,id itemid,integer quantity)
    {
        CCXR_Items__c item = [select id,CCXR_Item_Category__c,CCXR_Item_SubCategory__c from CCXR_Items__c where id=:itemid ];
        
        CCXR_Customer_Table_Status__c cts = [select CCXR_Customer__c,CCXR_Table__c,
                                             (select id,CCXR_Order_Status__c from CCXR_Orders__r
                                              where CCXR_Order_Status__c='Progress' ) from CCXR_Customer_Table_Status__c where
                                              id=:csn WITH SECURITY_ENFORCED];
        System.debug(cts);
        list<CCXR_Order__c > exorder = new  list<CCXR_Order__c>();
        exorder = cts.CCXR_Orders__r;
        if(exorder.size()==0)
        {
            CCXR_Order__c neworder = new CCXR_Order__c();
            neworder.CCXR_Customer_Table_Status__c=cts.Id;
            neworder.CCXR_Order_Status__c ='Progress';
            database.SaveResult dbs = database.insert(neworder,false);
            if (dbs.isSuccess()) {
                
                System.debug('Account Successfully inserted, Account Id is: ' + dbs.getId());
                neworderid =dbs.getId();
                
            }
        }
        CCXR_Order_Line_Item__c orderlineitem = new CCXR_Order_Line_Item__c ();    
        if(neworderid == null)
        {
            for(CCXR_Order__c ord:exorder)
            {
                orderlineitem.CCXR_Order_ID__c = ord.id ;
            }
        }
        else
        {
            orderlineitem.CCXR_Order_ID__c = neworderid ;
            
        }
        orderlineitem.CCXR_Item_ID__c = itemid;
        orderlineitem.CCXR_Quantity__c = quantity;
        orderlineitem.CCXR_Item_Category__c= item.CCXR_Item_Category__c;
        orderlineitem.CCXR_Item_SubCategory__c=item.CCXR_Item_SubCategory__c;
        insert orderlineitem;
        System.debug('OLI Successfully inserted, OLI Id is: ' + neworderid);
    }
    @AuraEnabled(cacheable=true)
    public static CCXR_Order__c  getCustomerTableStatusData(id csn)
    {
        CCXR_Order__c cts = [select id,Name from CCXR_Order__c where CCXR_Customer_Table_Status__r.id=:csn and CCXR_Order_Status__c='Progress' ];
        
        return cts;
    }
    
    @AuraEnabled
    public static CCXR_Order__c  getCustomerTableStatusData1(id csn)
    {
        boolean status=true;
        CCXR_Order__c cts = [select id,Name,CCXR_Order_Status__c from CCXR_Order__c where CCXR_Customer_Table_Status__r.id=:csn and CCXR_Order_Status__c='Progress' ];
        
        list<CCXR_Order_Line_Item__c>  orderst=[select CCXR_OrderLineItem_Status__c,CCXR_Order_ID__r.CCXR_Order_Status__c,
                                                CCXR_Order_ID__r.CCXR_Customer__c, CCXR_Order_ID__r.CCXR_Table__c,CCXR_Order_ID__r.Name,
                                                CCXR_Order_ID__r.CCXR_Grand_Total__c,CCXR_Order_ID__r.CCXR_Tax__c,CCXR_Order_ID__r.CCXR_OrderDiscount__c,
                                                CCXR_Order_ID__r.CCXR_Net_Total__c,
                                                Name,CCXR_Item_Name__c,CCXR_Quantity__c,CCXR_Price__c,CCXR_Total__c
                                                from CCXR_Order_Line_Item__c
                                                where  
                                                CCXR_Order_ID__C=:cts.id
                                               ];
        
        for(CCXR_Order_Line_Item__c oli:orderst)
        {
            system.debug(oli.Name);
            if(oli.CCXR_OrderLineItem_Status__c!='Served')
            {
                System.debug(oli.CCXR_OrderLineItem_Status__c);
                status=false;
                
            }
        }
        system.debug(status);
        if(status!=false)
        {
            cts.CCXR_Order_Status__c='Completed';
            update cts;
            
        }
        return cts;
    }
}

/*cts.CCXR_Order_Status__c='Completed';
update cts;*/
/*Order_Creation obj = new Order_Creation();
obj.createOrderAndOrderLines('a012w000019usWcAAI','a032w00000VJMsBAAX','a002w00000aDNcHAAW',2);*/