force-app/main/default/objects/CCXR_Chef_Status__c/CCXR_Chef_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Chef_Status</label>
    <nameField>
        <displayFormat>CSN-{0000}</displayFormat>
        <label>CCXR_Chef_Status Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Chef_Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Chef_Status__c/fields/CCXR_Chef_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Chef_Current_Status__c</fullName>
    <label>CCXR_Chef_Current_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Status__c/fields/CCXR_Restaurant_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Restaurant_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Restaurant_Employee__c.CCXR_Type_of_Employee__c</field>
            <operation>equals</operation>
            <value>Chef</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Chef_Statuses</relationshipLabel>
    <relationshipName>CCXR_Chef_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/CCXR_Customer__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>CCXR_Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Email__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Email__c</fullName>
    <label>CCXR_Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Feedback__c/CCXR_Feedback__c.object-meta.xml
<CustomObject>
    <label>CCXR_Feedback</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>CCXR_Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Feedback__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <formula>CCXR_Order__r.CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Feedback__c/fields/CCXR_Order__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order__c</fullName>
    <label>CCXR_Order</label>
    <referenceTo>CCXR_Order__c</referenceTo>
    <relationshipLabel>CCXR_Feedbacks</relationshipLabel>
    <relationshipName>CCXR_Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CCXR_Feedback__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Order__r.CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/CCXR_Items__c.object-meta.xml
<CustomObject>
    <label>CCXR_Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>CCXR_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Category__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Category__c</fullName>
    <label>CCXR_Item_Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Vegetarian</fullName>
            </value>
            <value>
                <fullName>Non-Vegetarian</fullName>
            </value>
            <value>
                <fullName>Beverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Name__c</fullName>
    <label>CCXR_Item Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Prep_Time__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Prep_Time__c</fullName>
    <label>CCXR_Item_Prep_Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 Min</fullName>
                <default>true</default>
                <label>10 Min</label>
            </value>
            <value>
                <fullName>15 Min</fullName>
            </value>
            <value>
                <fullName>20 Min</fullName>
            </value>
            <value>
                <fullName>25 Min</fullName>
            </value>
            <value>
                <fullName>40 Min</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Status__c</fullName>
    <label>CCXR_Item_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Out of Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_SubCategory__c</fullName>
    <label>CCXR_Item_SubCategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CCXR_Item_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Starters</fullName>
            </value>
            <value>
                <fullName>Soups</fullName>
            </value>
            <value>
                <fullName>Rice</fullName>
            </value>
            <value>
                <fullName>Curries</fullName>
            </value>
            <value>
                <fullName>Roti</fullName>
            </value>
            <value>
                <fullName>Desserts</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Milkshakes</fullName>
            </value>
            <value>
                <fullName>Ice Creams</fullName>
            </value>
            <value>
                <fullName>Sweets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Price__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Price__c</fullName>
    <label>CCXR_Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Serves__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Serves__c</fullName>
    <label>CCXR_Serves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/Item_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Item_Image_Link__c</fullName>
    <label>Item Image Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/CCXR_Order__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>CCXR_Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/CCXR_Restaurant_Employee__c.object-meta.xml
<CustomObject>
    <label>CCXR_Restaurant Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>CCXR_Restaurant Emp Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Restaurant Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Aadhar_Number__c</fullName>
    <label>CCXR_Aadhar Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Phone__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Phone__c</fullName>
    <label>CCXR_Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Type_of_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Type_of_Employee__c</fullName>
    <label>CCXR_Type_of_Employee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Restaurant Manager</fullName>
            </value>
            <value>
                <fullName>Front Desk Manager</fullName>
            </value>
            <value>
                <fullName>Chef</fullName>
            </value>
            <value>
                <fullName>Waiter</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Table__c/fields/Assigned_Waiter__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Waiter__c</fullName>
    <formula>CCXR_Restaurant_Employee__r.CCXR_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned Waiter</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Capacity__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Capacity__c</fullName>
    <label>CCXR_Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Restaurant_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Restaurant_Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Restaurant_Employee__c.CCXR_Type_of_Employee__c</field>
            <operation>equals</operation>
            <value>Waiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Tables</relationshipLabel>
    <relationshipName>CCXR_Tables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table_Status__c</fullName>
    <label>CCXR_Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
                <default>true</default>
                <label>Vacant</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/Table_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Table_Image_Link__c</fullName>
    <label>Table Image Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmployeeDataController.cls
/* 
Author Name : Pranay Naukarkar
Date Of Creation : 15/03/2023
Date last Modified : 03/04/2023
Purpose Of Class : To get the Data & delete records from CCXR_Restaurant_Employee__c,CCXR_Items__c,
					CCXR_Table__c,CCXR_Feedback__c which is used in LWC Component 
*/

public class EmployeeDataController 
{
    // To get the Data From Restaurant employee And Pass it to Javascript Controller "cheforderscreen.js" in lwc
	@AuraEnabled(cacheable=true)
    public static List<CCXR_Restaurant_Employee__c> getEmployeeList() 
    {
        return [SELECT Id, CCXR_Name__c, CCXR_Phone__c, CCXR_Email__c,CCXR_Aadhar_Number__c,
                CCXR_Type_of_Employee__c,(Select Name,CCXR_Chef_Current_Status__c from CCXR_Chef_Statuses__r)
                FROM CCXR_Restaurant_Employee__c];
    }
    
    //To get the Data of Items And Pass it to Javascript Controller "ccrItemsContent.js" in lwc
	@AuraEnabled(cacheable=true)
    public static List<CCXR_Items__c> getItemList() 
    {
        return [SELECT  id,CCXR_Item_Name__c, CCXR_Price__c,CCXR_Item_Category__c,CCXR_Item_SubCategory__c, CCXR_Item_Status__c,Item_Image_Link__c,
                CCXR_Item_Prep_Time__c,CCXR_Serves__c
                FROM CCXR_Items__c];
    }
    
    //To get the Data Of Tables And Pass it to Javascript Controller "ccrTableContent.js" in lwc
	@AuraEnabled(cacheable=true)
    public static List<CCXR_Table__c> getTableData1()
    {
        list<CCXR_Table__c> table=[select Name,CCXR_Capacity__c,Table_Image_Link__c,
                                   Assigned_Waiter__c,CCXR_Table_Status__c From CCXR_Table__c ORDER BY Name ASC];
        
        return table;
        
    }
    
    // To delete the Record Of a Restaurant employee used it in Javascript Controller "cheforderscreen.js" in lwc 
	@AuraEnabled
    public static void deleteEmp(Id selRecordId)
    {
        CCXR_Restaurant_Employee__c delEmp = [Select Name,id from CCXR_Restaurant_Employee__c 
                                              where id=:selRecordId];
        delete delEmp;
        
    }
    
    //To delete the Record Of a Items  used it in Javascript Controller "ccrItemsContent.js" in lwc
    @AuraEnabled
    public static void deleteItems(Id delRecordId)
    {
        CCXR_Items__c delitm = [Select Name,id from CCXR_Items__c 
                                where id=:delRecordId];
        delete delitm;
    }
    
    //To delete the Record Of a Table  used it in Javascript Controller "ccrTableContent.js" in lwc
    @AuraEnabled
    public static void deleteTable(Id tabRecordId)
    {
        list<CCXR_Table__c> delTab=[select Name,id From CCXR_Table__c
                                    where id=:tabRecordId];
        delete delTab;
        
    }
    
    // To get the Data From Feedback And Pass it to Javascript Controller "ccrFeedbackTable.js" in lwc
	@AuraEnabled(cacheable = true)
    public static List<CCXR_Feedback__c> getAllFeedback()
    {
        List<CCXR_Feedback__c> feedList =[select Name,CCXR_Customer__c,CCXR_Table__c,CCXR_Order__r.Name,
                                          CCXR_Food_Quality__c, CCXR_Service_Quality__c,CCXR_Suggestions__c
                                          from  CCXR_Feedback__c where CCXR_Customer__c!= NULL ];
        return feedList;
    }
    
}