force-app/main/default/objects/CCXR_Chef_Status__c/CCXR_Chef_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Chef_Status</label>
    <nameField>
        <displayFormat>CSN-{0000}</displayFormat>
        <label>CCXR_Chef_Status Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Chef_Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Chef_Status__c/fields/CCXR_Chef_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Chef_Current_Status__c</fullName>
    <label>CCXR_Chef_Current_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Status__c/fields/CCXR_Restaurant_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Restaurant_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Restaurant_Employee__c.CCXR_Type_of_Employee__c</field>
            <operation>equals</operation>
            <value>Chef</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Chef_Statuses</relationshipLabel>
    <relationshipName>CCXR_Chef_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/CCXR_Customer__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>CCXR_Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Email__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Email__c</fullName>
    <label>CCXR_Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Phone_Number__c</fullName>
    <label>CCXR_Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/No_Of_Persons__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Persons__c</fullName>
    <label>No Of Persons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/CCXR_Customer_Table_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer Table Status</label>
    <nameField>
        <displayFormat>CTSN-{0000}</displayFormat>
        <label>CCXR_CustomerTableStatusNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customer Table Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer</label>
    <referenceTo>CCXR_Customer__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Table</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Table__c.CCXR_Table_Status__c</field>
            <operation>equals</operation>
            <value>Vacant, Reserved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Table__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Feedback__c/CCXR_Feedback__c.object-meta.xml
<CustomObject>
    <label>CCXR_Feedback</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>CCXR_Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Feedback__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <formula>CCXR_Order__r.CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Feedback__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Order__r.CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/CCXR_Items__c.object-meta.xml
<CustomObject>
    <label>CCXR_Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>CCXR_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Name__c</fullName>
    <label>CCXR_Item Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Prep_Time__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Prep_Time__c</fullName>
    <label>CCXR_Item_Prep_Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 Min</fullName>
                <default>true</default>
                <label>10 Min</label>
            </value>
            <value>
                <fullName>15 Min</fullName>
            </value>
            <value>
                <fullName>20 Min</fullName>
            </value>
            <value>
                <fullName>25 Min</fullName>
            </value>
            <value>
                <fullName>40 Min</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Status__c</fullName>
    <label>CCXR_Item_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Out of Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Price__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Price__c</fullName>
    <label>CCXR_Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Serves__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Serves__c</fullName>
    <label>CCXR_Serves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/Item_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Item_Image_Link__c</fullName>
    <label>Item Image Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/CCXR_Order__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>CCXR_Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Customer_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer_Table_Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer Table Status</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Customer_Table_Status__c.Customer_Table_Status__c</field>
            <operation>equals</operation>
            <value>Occupied</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Customer_Table_Status__c</referenceTo>
    <relationshipLabel>CCXR_Orders</relationshipLabel>
    <relationshipName>CCXR_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/CCXR_Restaurant_Employee__c.object-meta.xml
<CustomObject>
    <label>CCXR_Restaurant Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>CCXR_Restaurant Emp Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Restaurant Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Aadhar_Number__c</fullName>
    <label>CCXR_Aadhar Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Phone__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Phone__c</fullName>
    <label>CCXR_Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Type_of_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Type_of_Employee__c</fullName>
    <label>CCXR_Type_of_Employee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Restaurant Manager</fullName>
            </value>
            <value>
                <fullName>Front Desk Manager</fullName>
            </value>
            <value>
                <fullName>Chef</fullName>
            </value>
            <value>
                <fullName>Waiter</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Table__c/fields/Assigned_Waiter__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Waiter__c</fullName>
    <formula>CCXR_Restaurant_Employee__r.CCXR_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned Waiter</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Capacity__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Capacity__c</fullName>
    <label>CCXR_Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Restaurant_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Restaurant_Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Restaurant_Employee__c.CCXR_Type_of_Employee__c</field>
            <operation>equals</operation>
            <value>Waiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Tables</relationshipLabel>
    <relationshipName>CCXR_Tables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table_Status__c</fullName>
    <label>CCXR_Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
                <default>true</default>
                <label>Vacant</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/Table_Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Table_Image_Link__c</fullName>
    <label>Table Image Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmployeeDataTest.cls
/* 
Author Name : Pranay Naukarkar
Date Of Creation : 31/03/2023
Date last Modified : 03/04/2023
Purpose of Test Class : To Test the Data that we are Fetching in Class EmployeeDataController
*/

@istest
private class EmployeeDataTest 
{
    // To test the data of "displayEmployeeData" method from Controller class "EmployeeDataController"
    @istest
    private static void displayEmployeeDataTest()
    {
         // Create test data
        CCXR_Restaurant_Employee__c emp = new CCXR_Restaurant_Employee__c();
        emp.CCXR_Name__c='Test Name';
        emp.CCXR_Phone__c='2457587847';
        emp.CCXR_Email__c='abc@gmail.com';
        emp.CCXR_Aadhar_Number__c='2255 2255 2255';
        emp.CCXR_Type_of_Employee__c='Chef';
        insert emp;
        
        CCXR_Chef_Status__c cf = new CCXR_Chef_Status__c();
        cf.CCXR_Chef_Current_Status__c='Available';
        cf.CCXR_Restaurant_Employee__c=emp.Id;
        insert cf;
        // Call the method being tested
        EmployeeDataController.getEmployeeList();
        List<CCXR_Restaurant_Employee__c> emplist=[SELECT Id, CCXR_Name__c, CCXR_Phone__c, CCXR_Email__c,CCXR_Aadhar_Number__c,
                                                   CCXR_Type_of_Employee__c
                                                   from CCXR_Restaurant_Employee__c where id=:emp.Id];
          // Verify the expected result
        system.assertEquals(1, emplist.size());
        
    }
    
    // To test the data of "getItemList" method from Controller class "EmployeeDataController"
    @isTest
    private static void getItemListTest()
    {
         // Create test data
        List<CCXR_Items__c> items= new List<CCXR_Items__c>();
        for(integer i=1;i<4;i++)
        {
            CCXR_Items__c item = new CCXR_Items__c();
            item.CCXR_Item_Name__c='Test Food'+ i;
            item.CCXR_Price__c=100;
            item.CCXR_Item_Status__c='Available';
            item.Item_Image_Link__c='https://i.pinimg.com/736x/c4/70/aa/c470aa518b4b87957ee31418f0559419.jpg';
            item.CCXR_Serves__c=2;
            item.CCXR_Item_Prep_Time__c='15 Min';
            items.add(item);
        }
        insert items;
        // Call the method being tested
        EmployeeDataController.getItemList();
        List<CCXR_Items__c> itmlist=[SELECT  id,CCXR_Item_Name__c, CCXR_Price__c, CCXR_Item_Status__c,Item_Image_Link__c,
                                     CCXR_Item_Prep_Time__c,CCXR_Serves__c
                                     FROM CCXR_Items__c];
        // Verify the expected result
        system.assertEquals(3, itmlist.size());
        
    } 
    
    // To test the data of "getTableData1" method from Controller class "EmployeeDataController"
    @isTest
    private static void getTableData1Test()
    {
         // Create test data
        list<CCXR_Table__c> uptables= new list<CCXR_Table__c>();
        for(integer i=1;i<4;i++)
        {
            CCXR_Table__c tb = new CCXR_Table__c();
            tb.CCXR_Capacity__c=4;
            tb.CCXR_Table_Status__c='Vacant';
            
            uptables.add(tb);
        }
        insert uptables;
        // Call the method being tested
        EmployeeDataController.getTableData1();
        list<CCXR_Table__c> tables=[select Name,CCXR_Capacity__c,Table_Image_Link__c,
                                    Assigned_Waiter__c,CCXR_Table_Status__c From CCXR_Table__c
                                   ];
        // Verify the expected result
        system.assertEquals(3, tables.size());
    }
    
    // To test the data of "deleteEmp" method from Controller class "EmployeeDataController"
    @isTest
    private static void deleteEmpTest() 
    {
         // Create test data
        CCXR_Restaurant_Employee__c emp = new CCXR_Restaurant_Employee__c();
        emp.CCXR_Name__c='Test Name';
        emp.CCXR_Phone__c='2457587847';
        emp.CCXR_Email__c='abc@gmail.com';
        emp.CCXR_Aadhar_Number__c='2255 2255 2255';
        emp.CCXR_Type_of_Employee__c='Chef';
        insert emp;
        
        // Call the method being tested
        EmployeeDataController.deleteEmp(emp.Id);
        List<CCXR_Restaurant_Employee__c> empList = [SELECT Id FROM CCXR_Restaurant_Employee__c WHERE Id = :emp.Id];
        
        // Verify the expected result
        System.assertEquals(0, empList.size());
    }
    
    // To test the data of "deleteItems" method from Controller class "EmployeeDataController"
    @isTest
    private static void deleteItemsTest()
    {
         // Create test data
        CCXR_Items__c item = new CCXR_Items__c();
        item.CCXR_Item_Name__c='Test Food Item';
        item.CCXR_Price__c=100;
        item.CCXR_Item_Status__c='Available';
        item.Item_Image_Link__c='https://i.pinimg.com/736x/c4/70/aa/c470aa518b4b87957ee31418f0559419.jpg';
        item.CCXR_Serves__c=2;
        item.CCXR_Item_Prep_Time__c='15 Min';
        insert item;
        
        // Call the method being tested
        EmployeeDataController.deleteItems(item.Id);
        List<CCXR_Items__c> itmList=[SELECT  id
                                     FROM CCXR_Items__c where id=:item.id];
        // Verify the expected result
        system.assertEquals(0, itmList.size());
    } 
    
    // To test the data of "deleteTable" method from Controller class "EmployeeDataController"
    @isTest
    private static void deleteTableTest()
    {
         // Create test data
        CCXR_Table__c tb = new CCXR_Table__c();
            tb.CCXR_Capacity__c=4;
            tb.CCXR_Table_Status__c='Vacant';
        insert tb ;
        
        // Call the method being tested
        EmployeeDataController.deleteTable(tb.Id);
        List<CCXR_Table__c> tbList=[SELECT  id
                                     FROM CCXR_Table__c where id=:tb.id];
        // Verify the expected result
        system.assertEquals(0, tbList.size());
    }
    
    // To test the data of "getAllFeedback" method from Controller class "EmployeeDataController"
     @isTest
    static void getAllFeedbackTest(){
        // Create test data
        CCXR_Customer__c cust = new CCXR_Customer__c();
        cust.CCXR_Name__c='Test Customer';
        cust.No_Of_Persons__c=4;
        cust.CCXR_Phone_Number__c='6303279407';
        insert cust;
        
        CCXR_Table__c tb = new CCXR_Table__c();
        tb.CCXR_Capacity__c=6;
        tb.CCXR_Table_Status__c='Vacant';
        insert tb;
        
        CCXR_Customer_Table_Status__c cst=new CCXR_Customer_Table_Status__c();
        cst.CCXR_Customer__c=cust.id;
        cst.CCXR_Table__c=tb.id;
            
        CCXR_Order__c order = new CCXR_Order__c();
        order.CCXR_Customer_Table_Status__c=cst.Id;
        insert order;
        
        CCXR_Feedback__c fd = new CCXR_Feedback__c();
        fd.CCXR_Order__c = order.Id;
        fd.CCXR_Food_Quality__c = 'Good';
        fd.CCXR_Service_Quality__c = 'Excellent';
        fd.CCXR_Suggestions__c = 'No suggestions';
        insert fd;
        
        // Call the method being tested
        EmployeeDataController.getAllFeedback();
        List<CCXR_Feedback__c> feedList = [Select Id,CCXR_Order__c,CCXR_Food_Quality__c,
                                           CCXR_Service_Quality__c,
                                           CCXR_Suggestions__c from CCXR_Feedback__c where id =:fd.id ];
        
       // Verify the expected result
        System.assertEquals(1, feedList.size()); 
    }
}