force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table_Status__c</fullName>
    <label>CCXR_Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
                <default>true</default>
                <label>Vacant</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/restimeinmins__c.field-meta.xml
<CustomField>
    <fullName>restimeinmins__c</fullName>
    <formula>FLOOR((NOW() - Time_Of_Reservation__c ) * 24 * 60)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>restimeinmins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SampleScheduler.cls
global class SampleScheduler implements Schedulable{
    global void execute(SchedulableContext SC)
    { 
        list<CCXR_Table__c> tables1=[select id,CCXR_Table_Status__c 
                                    from CCXR_Table__c 
                                    where CCXR_Table_Status__c='Reserved' and restimeinmins__c >=3];
        
       for(CCXR_Table__c c:tables1)
       {
           c.CCXR_Table_Status__c='Vacant';
           update c; 
       }
        
        
    }
 }