force-app/main/default/objects/CCX_On_Project__c/CCX_On_Project__c.object-meta.xml
<CustomObject>
    <label>CCX On Project</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>CCX On Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCX On Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCX_On_Project__c/fields/CCX_Project__c.field-meta.xml
<CustomField>
    <fullName>CCX_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCX Project</label>
    <referenceTo>CCX_Project__c</referenceTo>
    <relationshipLabel>CCX On Projects</relationshipLabel>
    <relationshipName>CCX_On_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCX_On_Project__c/fields/CCX_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>CCX_Start_Date__c</fullName>
    <label>CCX Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CCX_Project__c/CCX_Project__c.object-meta.xml
<CustomObject>
    <label>CCX Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>CCX Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCX Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCX_Project__c/fields/CCX_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>CCX_Project_Name__c</fullName>
    <label>CCX Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/displayProjects.cls
public class displayProjects {
    @AuraEnabled(cacheable=true)
    public static  void getProjects(){
       /* LISt<CCX_Project__c> project=[Select CCX_Project_Name__c,
                                      (select Name,CCX_Start_Date__c FROM CCX_On_Projects__r)
                                      From CCX_Project__c];
        system.debug('ID:'+project);
        return project;
        */
        
        for(CCX_Project__c u: [select CCX_Project_Name__c,(select Name,CCX_Start_Date__c FROM CCX_On_Projects__r) from CCX_Project__c])
		{   
    		for(CCX_On_Project__c c:u.CCX_On_Projects__r)
         	System.debug('Project Name:'+u.CCX_Project_Name__c+'   On Project Name:'+c.Name);
           
		}
        
        
    }
}