force-app/main/default/objects/CCXR_Chef_Orders__c/CCXR_Chef_Orders__c.object-meta.xml
<CustomObject>
    <label>CCXR_Chef Order</label>
    <nameField>
        <displayFormat>Chef_O-{0000}</displayFormat>
        <label>CCXR_Chef Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Chef Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Order Id</label>
    <referenceTo>CCXR_Order__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Order_Id__r.CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/CCXR_Customer__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>CCXR_Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/CCXR_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Phone_Number__c</fullName>
    <label>CCXR_Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer__c/fields/No_Of_Persons__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Persons__c</fullName>
    <label>No Of Persons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/CCXR_Customer_Table_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Customer Table Status</label>
    <nameField>
        <displayFormat>CTSN-{0000}</displayFormat>
        <label>CCXR_CustomerTableStatusNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Customer Table Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer</label>
    <referenceTo>CCXR_Customer__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Table</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Table__c.CCXR_Table_Status__c</field>
            <operation>equals</operation>
            <value>Vacant, Reserved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Table__c</referenceTo>
    <relationshipLabel>CCXR_Customer Table Statuses</relationshipLabel>
    <relationshipName>CCXR_Table_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Customer_Table_Status__c/fields/Customer_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Table_Status__c</fullName>
    <label>Customer Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Waiting</fullName>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Left</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/CCXR_Items__c.object-meta.xml
<CustomObject>
    <label>CCXR_Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>CCXR_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Name__c</fullName>
    <label>CCXR_Item Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Status__c</fullName>
    <label>CCXR_Item_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Out of Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Price__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Price__c</fullName>
    <label>CCXR_Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Serves__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Serves__c</fullName>
    <label>CCXR_Serves</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/CCXR_Order__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>CCXR_Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Customer__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Customer__r.CCXR_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Customer_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Customer_Table_Status__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Customer Table Status</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Customer_Table_Status__c.Customer_Table_Status__c</field>
            <operation>equals</operation>
            <value>Occupied</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Customer_Table_Status__c</referenceTo>
    <relationshipLabel>CCXR_Orders</relationshipLabel>
    <relationshipName>CCXR_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_Status__c</fullName>
    <label>CCXR_Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Progress</fullName>
                <default>true</default>
                <label>Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/CCXR_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000}</displayFormat>
        <label>CCXR_OrderLineItem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Name__c</fullName>
    <formula>CCXR_Item_ID__r.CCXR_Item_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Order_ID__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_ID__c</fullName>
    <label>CCXR_Order ID</label>
    <referenceTo>CCXR_Order__c</referenceTo>
    <relationshipLabel>CCXR_Order Line Items</relationshipLabel>
    <relationshipName>CCXR_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_OrderLineItem_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_OrderLineItem_Status__c</fullName>
    <label>CCXR_OrderLineItem_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Picked-up</fullName>
            </value>
            <value>
                <fullName>Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Price__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Price__c</fullName>
    <formula>CCXR_Item_ID__r.CCXR_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/CCXR_Restaurant_Employee__c.object-meta.xml
<CustomObject>
    <label>CCXR_Restaurant Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>CCXR_Restaurant Emp Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Restaurant Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Aadhar_Number__c</fullName>
    <label>CCXR_Aadhar Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Type_of_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Type_of_Employee__c</fullName>
    <label>CCXR_Type_of_Employee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Restaurant Manager</fullName>
            </value>
            <value>
                <fullName>Front Desk Manager</fullName>
            </value>
            <value>
                <fullName>Chef</fullName>
            </value>
            <value>
                <fullName>Waiter</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Capacity__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Capacity__c</fullName>
    <label>CCXR_Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Restaurant_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Restaurant_Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Restaurant_Employee__c.CCXR_Type_of_Employee__c</field>
            <operation>equals</operation>
            <value>Waiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Tables</relationshipLabel>
    <relationshipName>CCXR_Tables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Table_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table_Status__c</fullName>
    <label>CCXR_Table Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
                <default>true</default>
                <label>Vacant</label>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/displayorderlineitemsTest.cls
@istest
private class displayorderlineitemsTest 
{
    @IsTest
    static void testDisplayingOrder() 
    {
        // Create test data
        
          CCXR_Items__c items = new CCXR_Items__c();
        items.CCXR_Item_Name__c='Test Item';
        items.CCXR_Price__c=100;
        items.CCXR_Item_Status__c='Available';
        items.CCXR_Serves__c=2;
        insert items;
        
		CCXR_Restaurant_Employee__c rsc=new CCXR_Restaurant_Employee__c();
        rsc.CCXR_Name__c='Test Employee';
        rsc.CCXR_Type_of_Employee__c='Waiter';
        rsc.CCXR_Aadhar_Number__c='5328 6358 1129';
        insert rsc;
		        
        CCXR_Customer__c cust = new CCXR_Customer__c();
        cust.CCXR_Name__c='Test Customer';
        cust.No_Of_Persons__c=4;
        cust.CCXR_Phone_Number__c='6303279407';
        insert cust;
        
        CCXR_Table__c tb = new CCXR_Table__c();
        tb.CCXR_Capacity__c=6;
        tb.CCXR_Table_Status__c='Vacant';
        tb.CCXR_Restaurant_Employee__c=rsc.Id;
        insert tb;
        
        CCXR_Customer_Table_Status__c cts = new CCXR_Customer_Table_Status__c();
         cts.CCXR_Customer__c=cust.id;
        cts.CCXR_Table__c=tb.Id;
        cts.Customer_Table_Status__c='Occupied';
        insert cts;
        
        CCXR_Order__c order = new CCXR_Order__c(CCXR_Customer_Table_Status__c = cts.Id,CCXR_Order_Status__c = 'Progress');
        insert order;
        
        CCXR_Order_Line_Item__c orderItem = new CCXR_Order_Line_Item__c(
            CCXR_OrderLineItem_Status__c = 'Pending',
            CCXR_Order_ID__c = order.Id,
            CCXR_Quantity__c = 1.0
        );
        insert orderItem;
        
        // Call the method with the test data
      
        List<CCXR_Order_Line_Item__c> result = displayingorderlineitems.displayingorder(cts.Id);
        
        // Verify the result
        System.assertEquals(1, result.size());
        CCXR_Order_Line_Item__c item = result[0];
    }
    @isTest
    static void testDeleteOrderLineItems() {
        // Create test data
        CCXR_Order__c order = new CCXR_Order__c();
        insert order;
        CCXR_Order_Line_Item__c orderItem = new CCXR_Order_Line_Item__c(
            CCXR_Order_Id__c = order.Id,
            CCXR_OrderLineItem_Status__c = 'Pending'
        );
        insert orderItem;
        CCXR_Chef_Orders__c chefOrder = new CCXR_Chef_Orders__c(
            orderlineId__c = orderItem.Id
        );
        insert chefOrder;
        
        // Call the method to be tested       
        List<CCXR_Order_Line_Item__c> deletedOrderItems = displayingorderlineitems.deteleorderlineitems(orderItem.Id);
        
        // Verify the method results
        System.assertEquals(1, deletedOrderItems.size(), 'One order item should have been deleted');
        System.assertEquals(orderItem.Id, deletedOrderItems[0].Id, 'The deleted order item should have the correct Id');
        
        // Verify that related chef orders were deleted
        List<CCXR_Chef_Orders__c> chefOrders = [SELECT Id FROM CCXR_Chef_Orders__c WHERE orderlineId__c = :orderItem.Id];
        System.assertEquals(0, chefOrders.size(), 'Related chef orders should have been deleted');
        
        // Verify that other order items were not deleted
        List<CCXR_Order_Line_Item__c> remainingOrderItems = [SELECT Id FROM CCXR_Order_Line_Item__c];
        System.assertEquals(0, remainingOrderItems.size(), 'Other order items should not have been deleted');
    }
}