force-app/main/default/objects/CCXR_Chef_Orders__c/CCXR_Chef_Orders__c.object-meta.xml
<CustomObject>
    <label>CCXR_Chef Order</label>
    <nameField>
        <displayFormat>Chef_O-{0000}</displayFormat>
        <label>CCXR_Chef Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Chef Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/Assignedtochef__c.field-meta.xml
<CustomField>
    <fullName>Assignedtochef__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/button1__c.field-meta.xml
<CustomField>
    <fullName>button1__c</fullName>
    <defaultValue>true</defaultValue>
    <label>button1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/button__c.field-meta.xml
<CustomField>
    <fullName>button__c</fullName>
    <defaultValue>false</defaultValue>
    <label>button</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Accepted_By_Chef__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Accepted_By_Chef__c</fullName>
    <label>CCXR_Accepted_By_Chef</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Items_ID__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Items_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Items ID</label>
    <referenceTo>CCXR_Items__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Order Id</label>
    <referenceTo>CCXR_Order__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Quantity__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Quantity__c</fullName>
    <label>CCXR_Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Order_Id__r.CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/Order_status__c.field-meta.xml
<CustomField>
    <fullName>Order_status__c</fullName>
    <label>Order status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Picked-up</fullName>
            </value>
            <value>
                <fullName>Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Status__c/CCXR_Chef_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Chef_Status</label>
    <nameField>
        <displayFormat>CSN-{0000}</displayFormat>
        <label>CCXR_Chef_Status Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Chef_Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Chef_Status__c/fields/CCXR_Chef_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Chef_Current_Status__c</fullName>
    <label>CCXR_Chef_Current_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Status__c/fields/CCXR_Restaurant_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Restaurant_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Restaurant_Employee__c.CCXR_Type_of_Employee__c</field>
            <operation>equals</operation>
            <value>Chef</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Chef_Statuses</relationshipLabel>
    <relationshipName>CCXR_Chef_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/CCXR_Items__c.object-meta.xml
<CustomObject>
    <label>CCXR_Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>CCXR_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Category__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Category__c</fullName>
    <label>CCXR_Item_Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Vegetarian</fullName>
            </value>
            <value>
                <fullName>Non-Vegetarian</fullName>
            </value>
            <value>
                <fullName>Beverage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Name__c</fullName>
    <label>CCXR_Item Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/CCXR_Order__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>CCXR_Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/CCXR_Restaurant_Employee__c.object-meta.xml
<CustomObject>
    <label>CCXR_Restaurant Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>CCXR_Restaurant Emp Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Restaurant Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Type_Of_Chef__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Type_Of_Chef__c</fullName>
    <label>CCXR_Type Of Chef</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CCXR_Type_of_Employee__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vegetarian</fullName>
            </value>
            <value>
                <fullName>Non-Vegetarian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Type_of_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Type_of_Employee__c</fullName>
    <label>CCXR_Type_of_Employee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Restaurant Manager</fullName>
            </value>
            <value>
                <fullName>Front Desk Manager</fullName>
            </value>
            <value>
                <fullName>Chef</fullName>
            </value>
            <value>
                <fullName>Waiter</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Restaurant_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Restaurant_Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Restaurant_Employee__c.CCXR_Type_of_Employee__c</field>
            <operation>equals</operation>
            <value>Waiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Tables</relationshipLabel>
    <relationshipName>CCXR_Tables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Chefscreencontroller.cls
public with sharing class Chefscreencontroller 
{
    /*
 Class Name : Chefscreencontroller,
 Author     : Katapally uday kumar,
 Date Of Creation: 13/03.2023,
 Last Modified Date : 04/03/2023,
 Purpose Of Class : The purpose of this class is to get the cheforders 
 */
    @AuraEnabled(cacheable = true)
    public static List<CCXR_Chef_Orders__c> getAllcheforders(){
        List<CCXR_Chef_Orders__c> accList =[Select Id,CCXR_Order_Id__c,CCXR_Quantity__c,Assignedtochef__r.Name,CCXR_Items_ID__r.CCXR_Item_Category__c,
        CCXR_Items_ID__c,CCXR_Items_ID__r.CCXR_Item_Name__c,CCXR_Table__c,Order_status__c,button__c,button1__c,Assignedtochef__c,CCXR_Accepted_By_Chef__c,CCXR_Order_Id__r.Name FROM CCXR_Chef_Orders__c where Order_status__c='Pending' or Order_status__c='Preparing' or Order_status__c='Ready'];
        return accList;
    }
    @AuraEnabled
    public static Integer updatecheforderstatus(Id cat,Id cat1,boolean but1,boolean but2 )
    {
        CCXR_Chef_Orders__c acc = new CCXR_Chef_Orders__c(Id = cat);
        acc.Order_status__c ='Preparing';
        acc.Assignedtochef__c=cat1;
        acc.button__c=but1;
        acc.button1__c=but2;
        update acc;
       
        List<CCXR_Chef_Orders__c> chefflist1 =[Select Id,Assignedtochef__c,
        Order_status__c FROM CCXR_Chef_Orders__c
        where Assignedtochef__c=:cat1 and Order_status__c='Preparing'];
        Integer nooforders=chefflist1.size();
        
        return nooforders;
    }
    @AuraEnabled
    public static CCXR_Chef_Orders__c updatecheforderstatus1(Id cat,boolean but2)
    {
        CCXR_Chef_Orders__c acc = new CCXR_Chef_Orders__c(Id = cat);
        acc.Order_status__c ='Ready';
        acc.button1__c=but2;
        update acc;
        CCXR_Chef_Orders__c chefacc=[select id,Assignedtochef__c from CCXR_Chef_Orders__c where id=:acc.id ];
        return chefacc;
    }
    @AuraEnabled
    public static void updatechefemployeebusy(Id cid)
    {
        CCXR_Chef_Status__c chefsta=[select id ,CCXR_Chef_Current_Status__c from CCXR_Chef_Status__c where CCXR_Restaurant_Employee__c=:cid];
        chefsta.CCXR_Chef_Current_Status__c ='Busy';
        update chefsta;
    }
      @AuraEnabled
    public static void updatechefemployeeavailable(Id cid)
    {
        CCXR_Chef_Status__c chefsta=[select id ,CCXR_Chef_Current_Status__c from CCXR_Chef_Status__c where CCXR_Restaurant_Employee__c=:cid];
        chefsta.CCXR_Chef_Current_Status__c ='Available';
        update chefsta;
    }
    @AuraEnabled(cacheable=true)
    public static List<CCXR_Restaurant_Employee__c> getempnames(String chefname) {
      
      return [SELECT Id, Name,CCXR_Name__c,CCXR_Type_Of_Chef__c FROM CCXR_Restaurant_Employee__c where CCXR_Type_of_Employee__c='Chef' AND Id IN (SELECT CCXR_Restaurant_Employee__c FROM CCXR_Chef_Status__c WHERE CCXR_Chef_Current_Status__c= 'Available')];
    }
}