force-app/main/default/objects/CCXR_Chef_Orders__c/CCXR_Chef_Orders__c.object-meta.xml
<CustomObject>
    <label>CCXR_Chef Order</label>
    <nameField>
        <displayFormat>Chef_O-{0000}</displayFormat>
        <label>CCXR_Chef Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Chef Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/Assignedtochef__c.field-meta.xml
<CustomField>
    <fullName>Assignedtochef__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/button1__c.field-meta.xml
<CustomField>
    <fullName>button1__c</fullName>
    <defaultValue>true</defaultValue>
    <label>button1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/button__c.field-meta.xml
<CustomField>
    <fullName>button__c</fullName>
    <defaultValue>false</defaultValue>
    <label>button</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Items_ID__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Items_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Items ID</label>
    <referenceTo>CCXR_Items__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Order Id</label>
    <referenceTo>CCXR_Order__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Quantity__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Quantity__c</fullName>
    <label>CCXR_Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/Order_status__c.field-meta.xml
<CustomField>
    <fullName>Order_status__c</fullName>
    <label>Order status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Picked-up</fullName>
            </value>
            <value>
                <fullName>Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Status__c/CCXR_Chef_Status__c.object-meta.xml
<CustomObject>
    <label>CCXR_Chef_Status</label>
    <nameField>
        <displayFormat>CSN-{0000}</displayFormat>
        <label>CCXR_Chef_Status Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Chef_Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Chef_Status__c/fields/CCXR_Chef_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Chef_Current_Status__c</fullName>
    <label>CCXR_Chef_Current_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Status__c/fields/CCXR_Restaurant_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Restaurant_Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Restaurant_Employee__c.CCXR_Type_of_Employee__c</field>
            <operation>equals</operation>
            <value>Chef</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Chef_Statuses</relationshipLabel>
    <relationshipName>CCXR_Chef_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/CCXR_Restaurant_Employee__c.object-meta.xml
<CustomObject>
    <label>CCXR_Restaurant Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>CCXR_Restaurant Emp Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Restaurant Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Type_of_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Type_of_Employee__c</fullName>
    <label>CCXR_Type_of_Employee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Restaurant Manager</fullName>
            </value>
            <value>
                <fullName>Front Desk Manager</fullName>
            </value>
            <value>
                <fullName>Chef</fullName>
            </value>
            <value>
                <fullName>Waiter</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChefscreencontrollerTest.cls
@isTest
private class ChefscreencontrollerTest {
    @isTest
    
    private static void testGetAllChefOrders() {
        // Test data setup
        CCXR_Chef_Orders__c order1 = new CCXR_Chef_Orders__c(
            CCXR_Order_Id__c = 'a022w00000nh3GpAAI',
            CCXR_Quantity__c = 1,
            CCXR_Items_ID__c = 'a002w00000aFdgDAAS',
            
            Order_status__c = 'Preparing'
        );
        CCXR_Chef_Orders__c order2 = new CCXR_Chef_Orders__c(
            CCXR_Order_Id__c = 'a022w00000nh3GpAAI',
            CCXR_Quantity__c = 2,
            CCXR_Items_ID__c = 'a002w00000aFdgDAAS',
            
            Order_status__c = 'Preparing'
        );
        insert new List<CCXR_Chef_Orders__c> { order1, order2 };
            
            // Test method execution
            List<CCXR_Chef_Orders__c> orders = Chefscreencontroller.getAllcheforders();
        
        // Assertion
        System.assertEquals(2, orders.size());
    }
    @isTest
    private static void testUpdateChefOrderStatus()
    {
         CCXR_Chef_Orders__c order = new CCXR_Chef_Orders__c();
        order.Order_status__c = 'Pending';
        order.CCXR_Order_Id__c = 'a022w00000nh3GpAAI';
        insert order;
        
        // Create a test chef employee record
        CCXR_Restaurant_Employee__c employee = new CCXR_Restaurant_Employee__c();
        employee.CCXR_Type_of_Employee__c = 'Chef';
        employee.CCXR_Name__c = 'Test Chef';
        insert employee;
        //calling apex class
        Chefscreencontroller.updatecheforderstatus(order.Id, employee.Id, true, false);
        
        // Retrieve the updated record and verify 
        CCXR_Chef_Orders__c updatedOrder = [SELECT Order_status__c, Assignedtochef__c, button__c, button1__c FROM 
                                            CCXR_Chef_Orders__c WHERE Id =:order.Id];
        System.assertEquals('Preparing', updatedOrder.Order_status__c);
        System.assertEquals(employee.Id, updatedOrder.Assignedtochef__c);
        System.assertEquals(true, updatedOrder.button__c);
        System.assertEquals(false, updatedOrder.button1__c);
    }
    @isTest
    private static void testUpdateChefOrderStatus1() {
        // Test data setup
        CCXR_Chef_Orders__c order = new CCXR_Chef_Orders__c(
            CCXR_Order_Id__c = 'a022w00000nh3GpAAI',
            CCXR_Quantity__c = 1,
            CCXR_Items_ID__c = 'a002w00000aFdgDAAS',
            
            Order_status__c = 'Preparing'
        );
        insert order;
        
        // Test method execution
        Chefscreencontroller.updatecheforderstatus1(order.Id, true);
        order = [SELECT Id, Order_status__c, button1__c FROM CCXR_Chef_Orders__c WHERE Id = :order.Id];
        
        // Assertion
        System.assertEquals('Ready', order.Order_status__c);
        System.assertEquals(true, order.button1__c);
    }
    @isTest
    private static void testUpdateChefEmployeeBusy() 
    {
        // Test data setup
        CCXR_Restaurant_Employee__c emp = new CCXR_Restaurant_Employee__c();
        emp.CCXR_Name__c = 'Test Chef';
        emp.CCXR_Type_of_Employee__c = 'Chef';
        
        insert emp;
        
        CCXR_Chef_Status__c chefStatus = new CCXR_Chef_Status__c();
        chefStatus.CCXR_Restaurant_Employee__c = emp.Id;
        chefStatus.CCXR_Chef_Current_Status__c = 'Available';
        
        insert chefStatus;
        
        
        
        
        //Arrange
        CCXR_Restaurant_Employee__c emp1 = [SELECT Id FROM CCXR_Restaurant_Employee__c WHERE 
                                            CCXR_Name__c ='Test Chef' LIMIT 1];
        
        
        
        Chefscreencontroller.updatechefemployeebusy(emp1.Id);
        
        
        //Assert
        CCXR_Chef_Status__c chefStatus1 = [SELECT CCXR_Chef_Current_Status__c FROM CCXR_Chef_Status__c 
                                           WHERE CCXR_Restaurant_Employee__c =: emp1.Id LIMIT 1];
        System.assertEquals('Busy', chefStatus1.CCXR_Chef_Current_Status__c);
        
        
        
    }
     @isTest
    private static void testupdatechefemployeeavailable() 
    {
         CCXR_Restaurant_Employee__c emp = new CCXR_Restaurant_Employee__c();
        emp.CCXR_Name__c = 'Test Chef';
        emp.CCXR_Type_of_Employee__c = 'Chef';
        insert emp;
        
        Chefscreencontroller.updatechefemployeeavailable(emp.Id);
        CCXR_Chef_Status__c chefsta=[select id ,CCXR_Chef_Current_Status__c from CCXR_Chef_Status__c where CCXR_Restaurant_Employee__c=:emp.id];
        chefsta.CCXR_Chef_Current_Status__c ='Available';
        update chefsta;
        
        
        
    }
}