force-app/main/default/objects/CCXR_Chef_Orders__c/CCXR_Chef_Orders__c.object-meta.xml
<CustomObject>
    <label>CCXR_Chef Order</label>
    <nameField>
        <displayFormat>Chef_O-{0000}</displayFormat>
        <label>CCXR_Chef Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Chef Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Order Id</label>
    <referenceTo>CCXR_Order__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/Order_status__c.field-meta.xml
<CustomField>
    <fullName>Order_status__c</fullName>
    <label>Order status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Picked-up</fullName>
            </value>
            <value>
                <fullName>Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/orderlineId__c.field-meta.xml
<CustomField>
    <fullName>orderlineId__c</fullName>
    <label>orderlineId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/CCXR_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000}</displayFormat>
        <label>CCXR_OrderLineItem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Item_ID__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Item ID</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>CCXR_Items__c.CCXR_Item_Category__c</field>
            <operation>equals</operation>
            <valueField>$Source.CCXR_Item_Category__c</valueField>
        </filterItems>
        <filterItems>
            <field>CCXR_Items__c.CCXR_Item_SubCategory__c</field>
            <operation>equals</operation>
            <valueField>$Source.CCXR_Item_SubCategory__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Items__c</referenceTo>
    <relationshipLabel>CCXR_Order Line Items</relationshipLabel>
    <relationshipName>CCXR_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_Order_ID__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_ID__c</fullName>
    <label>CCXR_Order ID</label>
    <referenceTo>CCXR_Order__c</referenceTo>
    <relationshipLabel>CCXR_Order Line Items</relationshipLabel>
    <relationshipName>CCXR_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CCXR_Order_Line_Item__c/fields/CCXR_OrderLineItem_Status__c.field-meta.xml
<CustomField>
    <fullName>CCXR_OrderLineItem_Status__c</fullName>
    <label>CCXR_OrderLineItem_Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Picked-up</fullName>
            </value>
            <value>
                <fullName>Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChefOrderHelper.cls
public class ChefOrderHelper
{
    public static void updateStatus(List<CCXR_Chef_Orders__c> chefOrdersList)
    { 
        list<CCXR_Order_Line_Item__c> upoli= new list<CCXR_Order_Line_Item__c>();
        for(CCXR_Chef_Orders__c cord:chefOrdersList)
        {
            list<CCXR_Order_Line_Item__c> oli=[select id,Name,CCXR_Item_ID__c,CCXR_Order_ID__c 
                                               from CCXR_Order_Line_Item__c
                                               where CCXR_Order_ID__c=:cord.CCXR_Order_Id__c and 
                                               Id=:cord.orderlineId__c ];
            for(CCXR_Order_Line_Item__c ol:oli)
            {
                ol.CCXR_OrderLineItem_Status__c=cord.Order_status__c; 
                upoli.add(ol);
            }
           
        }
        update upoli; 
    } 
}