force-app/main/default/objects/CCXR_Chef_Orders__c/CCXR_Chef_Orders__c.object-meta.xml
<CustomObject>
    <label>CCXR_Chef Order</label>
    <nameField>
        <displayFormat>Chef_O-{0000}</displayFormat>
        <label>CCXR_Chef Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Chef Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/Assignedtochef__c.field-meta.xml
<CustomField>
    <fullName>Assignedtochef__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/button1__c.field-meta.xml
<CustomField>
    <fullName>button1__c</fullName>
    <defaultValue>true</defaultValue>
    <label>button1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/button__c.field-meta.xml
<CustomField>
    <fullName>button__c</fullName>
    <defaultValue>false</defaultValue>
    <label>button</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Accepted_By_Chef__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Accepted_By_Chef__c</fullName>
    <label>CCXR_Accepted_By_Chef</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Items_ID__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Items_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Items ID</label>
    <referenceTo>CCXR_Items__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Order Id</label>
    <referenceTo>CCXR_Order__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Quantity__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Quantity__c</fullName>
    <label>CCXR_Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/Order_status__c.field-meta.xml
<CustomField>
    <fullName>Order_status__c</fullName>
    <label>Order status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Picked-up</fullName>
            </value>
            <value>
                <fullName>Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/CCXR_Items__c.object-meta.xml
<CustomObject>
    <label>CCXR_Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>CCXR_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Name__c</fullName>
    <label>CCXR_Item Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/CCXR_Order__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>CCXR_Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/CCXR_Restaurant_Employee__c.object-meta.xml
<CustomObject>
    <label>CCXR_Restaurant Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>CCXR_Restaurant Emp Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Restaurant Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/customTableTest.cls
@isTest
public class customTableTest {

    @isTest
    static void testGetAllAccounts() 
    {
        // Create test data
        CCXR_Chef_Orders__c order = new CCXR_Chef_Orders__c(
            CCXR_Order_Id__c = '123',
            CCXR_Quantity__c = 2,
            CCXR_Items_ID__c = '456',
           
            Order_status__c = 'Pending'
        );
        insert order;

        // Call the method being tested
        List<CCXR_Chef_Orders__c> result = customTable.getAllAccounts();

        // Verify that the expected results are returned
        System.assertEquals(1, result.size());
        System.assertEquals(order.Id, result[0].Id);
        System.assertEquals(order.CCXR_Order_Id__c, result[0].CCXR_Order_Id__c);
        System.assertEquals(order.CCXR_Quantity__c, result[0].CCXR_Quantity__c);
        System.assertEquals(order.Assignedtochef__r.Name, result[0].Assignedtochef__r.Name);
        System.assertEquals(order.CCXR_Items_ID__c, result[0].CCXR_Items_ID__c);
        System.assertEquals(order.CCXR_Items_ID__r.CCXR_Item_Name__c, result[0].CCXR_Items_ID__r.CCXR_Item_Name__c);
       
        System.assertEquals(order.Order_status__c, result[0].Order_status__c);
        System.assertEquals(order.button__c, result[0].button__c);
        System.assertEquals(order.button1__c, result[0].button1__c);
        System.assertEquals(order.Assignedtochef__c, result[0].Assignedtochef__c);
        System.assertEquals(order.CCXR_Accepted_By_Chef__c, result[0].CCXR_Accepted_By_Chef__c);
        System.assertEquals(order.CCXR_Order_Id__r.Name, result[0].CCXR_Order_Id__r.Name);
    }
}