force-app/main/default/objects/CCXR_Chef_Orders__c/CCXR_Chef_Orders__c.object-meta.xml
<CustomObject>
    <label>CCXR_Chef Order</label>
    <nameField>
        <displayFormat>Chef_O-{0000}</displayFormat>
        <label>CCXR_Chef Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Chef Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/assigned_waiter__c.field-meta.xml
<CustomField>
    <fullName>assigned_waiter__c</fullName>
    <formula>CCXR_Order_Id__r.CCXR_Customer_Table_Status__r.CCXR_Table__r.CCXR_Restaurant_Employee__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>assigned waiter</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/Assignedtochef__c.field-meta.xml
<CustomField>
    <fullName>Assignedtochef__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/button3__c.field-meta.xml
<CustomField>
    <fullName>button3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>button3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/button4__c.field-meta.xml
<CustomField>
    <fullName>button4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>button4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Accepted_By_Chef__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Accepted_By_Chef__c</fullName>
    <label>CCXR_Accepted_By_Chef</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Items_ID__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Items_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Items ID</label>
    <referenceTo>CCXR_Items__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Order_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCXR_Order Id</label>
    <referenceTo>CCXR_Order__c</referenceTo>
    <relationshipLabel>CCXR_Chef Orders</relationshipLabel>
    <relationshipName>CCXR_Chef_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Order_Id__r.CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Chef_Orders__c/fields/Order_status__c.field-meta.xml
<CustomField>
    <fullName>Order_status__c</fullName>
    <label>Order status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Picked-up</fullName>
            </value>
            <value>
                <fullName>Served</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Items__c/CCXR_Items__c.object-meta.xml
<CustomObject>
    <label>CCXR_Items</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>CCXR_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Items__c/fields/CCXR_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Item_Name__c</fullName>
    <label>CCXR_Item Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Order__c/CCXR_Order__c.object-meta.xml
<CustomObject>
    <label>CCXR_Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>CCXR_Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Order__c/fields/CCXR_Table__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Table__c</fullName>
    <formula>CCXR_Customer_Table_Status__r.CCXR_Table__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CCXR_Table</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/CCXR_Restaurant_Employee__c.object-meta.xml
<CustomObject>
    <label>CCXR_Restaurant Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>CCXR_Restaurant Emp Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Restaurant Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Table__c/fields/Assigned_Waiter__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Waiter__c</fullName>
    <formula>CCXR_Restaurant_Employee__r.CCXR_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned Waiter</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/waiterScreenController.cls
//Author:R Yaswanth Reddy
//Date Creation :20/03/2023
//Date Modified:24/03/2023
//Purpose of the Class: Order status field is set to 'Ready' or 'Picked-up'.
//This Class contains 3 methods

public class waiterScreenController
{
       @AuraEnabled(cacheable = true)
    public static List<CCXR_Chef_Orders__c> getAllAccountss(){
        // Retrieve  records with Ready' or 'Picked-up status
        List<CCXR_Chef_Orders__c> accList =[Select Id,CCXR_Order_Id__c,CCXR_Table__c,
        CCXR_Items_ID__c,Order_status__c,button3__c,button4__c,Assignedtochef__r.Name,assigned_waiter__c,CCXR_Accepted_By_Chef__c,CCXR_Items_ID__r.CCXR_Item_Name__c,CCXR_Order_Id__r.Name FROM CCXR_Chef_Orders__c where Order_status__c in ('Ready','Picked-up')];
        return accList;
        // Return the list of customer table records
    }
    /*
* @AuraEnabled - This annotation enables the method to be called by an Aura component.
* Updates the Order_status__c field of the CCXR_Chef_Orders__c record with the provided Id to 'Picked-up'.
* @param cat - The Id of the CCXR_Chef_Orders__c record to update.
* @param but1 - A boolean value to update the button3__c field of the CCXR_Chef_Orders__c record.
* @param but2 - A boolean value to update the button4__c field of the CCXR_Chef_Orders__c record.
*/
    @AuraEnabled
    public static void statuspick(Id cat,boolean but1,boolean but2)
    {
        CCXR_Chef_Orders__c acc = new CCXR_Chef_Orders__c(Id = cat);
        acc.Order_status__c ='Picked-up';
        acc.button3__c=but1;
        acc.button4__c=but2;
        update acc;
        

}
   /*
* @AuraEnabled - This annotation enables the method to be called by an Aura component.
* Updates the Order_status__c field of the CCXR_Chef_Orders__c record with the provided Id to 'Served'.
* @param cat - The Id of the CCXR_Chef_Orders__c record to update.
* @param but2 - A boolean value to update the button4__c field of the CCXR_Chef_Orders__c record.
*/
@AuraEnabled
public static void statusser(Id cat,boolean but2)
{
    CCXR_Chef_Orders__c acc = new CCXR_Chef_Orders__c(Id = cat);
    acc.Order_status__c ='Served';
  
    acc.button4__c=but2;
    update acc;
        

}
}