force-app/main/default/objects/CCXR_Restaurant_Employee__c/CCXR_Restaurant_Employee__c.object-meta.xml
<CustomObject>
    <label>CCXR_Restaurant Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>CCXR_Restaurant Emp Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Restaurant Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Name__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Name__c</fullName>
    <label>CCXR_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCXR_Restaurant_Employee__c/fields/CCXR_Type_of_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Type_of_Employee__c</fullName>
    <label>CCXR_Type_of_Employee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Restaurant Manager</fullName>
            </value>
            <value>
                <fullName>Front Desk Manager</fullName>
            </value>
            <value>
                <fullName>Chef</fullName>
            </value>
            <value>
                <fullName>Waiter</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCXR_Table__c/CCXR_Table__c.object-meta.xml
<CustomObject>
    <label>CCXR_Table</label>
    <nameField>
        <displayFormat>TABLE-{0000}</displayFormat>
        <label>CCXR_Table ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCXR_Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCXR_Table__c/fields/CCXR_Restaurant_Employee__c.field-meta.xml
<CustomField>
    <fullName>CCXR_Restaurant_Employee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>CCXR_Restaurant Employee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CCXR_Restaurant_Employee__c.CCXR_Type_of_Employee__c</field>
            <operation>equals</operation>
            <value>Waiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CCXR_Restaurant_Employee__c</referenceTo>
    <relationshipLabel>CCXR_Tables</relationshipLabel>
    <relationshipName>CCXR_Tables</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WaiterAssignmentsTest.cls
@isTest
public class WaiterAssignmentsTest 
{    
    static testMethod void testWaiterAssignments() 
     {       
        // Create test data
        CCXR_Restaurant_Employee__c employee = new CCXR_Restaurant_Employee__c(CCXR_Name__c='Lohitha',CCXR_Type_of_Employee__c='Waiter');
        insert employee;        
         List<CCXR_Table__c> tables = new List<CCXR_Table__c>();
         for (Integer i = 0; i < 5; i++)
         {
           CCXR_Table__c table = new CCXR_Table__c();          
           table.CCXR_Restaurant_Employee__c = employee.Id;
           tables.add(table);
         }
         insert tables;            
         // Trigger update that should result in an error
            tables[0].CCXR_Restaurant_Employee__c = null;
            tables[1].CCXR_Restaurant_Employee__c = employee.Id;
            tables[2].CCXR_Restaurant_Employee__c = employee.Id;
            tables[3].CCXR_Restaurant_Employee__c = employee.Id;
            tables[4].CCXR_Restaurant_Employee__c = employee.Id;                 
            // Verify        
             try
             {
                update tables;
             } 
            catch (DmlException e) 
            {
            // check if the error message is as expected
            String expectedErrorMessage = 'Cannot assign more than 4 tables to the same employee.';
            System.assert(e.getMessage().contains(expectedErrorMessage), 'Error message should be: ' + expectedErrorMessage);
            }
     } 
}