force-app/main/default/objects/CCX_Project__c/CCX_Project__c.object-meta.xml
<CustomObject>
    <label>CCX Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>CCX Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCX Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCX_Project_Manager__c/CCX_Project_Manager__c.object-meta.xml
<CustomObject>
    <label>CCX Project Manager</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>CCX Project Manager ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCX Project Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCX_Project_Manager__c/fields/CCX_Project__c.field-meta.xml
<CustomField>
    <fullName>CCX_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCX Project</label>
    <referenceTo>CCX_Project__c</referenceTo>
    <relationshipLabel>CCX Project Managers</relationshipLabel>
    <relationshipName>CCX_Project_Managers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCX_Project_Manager__c/fields/CCX_User_Account__c.field-meta.xml
<CustomField>
    <fullName>CCX_User_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CCX User Account</label>
    <referenceTo>CCX_User_Account__c</referenceTo>
    <relationshipLabel>CCX Project Managers</relationshipLabel>
    <relationshipName>CCX_Project_Managers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCX_User_Account__c/CCX_User_Account__c.object-meta.xml
<CustomObject>
    <label>CCX User Account</label>
    <nameField>
        <displayFormat>UAN-{0000}</displayFormat>
        <label>CCX User Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CCX User Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectmanagerController.cls
public with sharing class ProjectmanagerController

{
    @AuraEnabled(cacheable=true)
    public static List<CCX_Project_Manager__c>  getprojectmanagerrecords()
    {
        list<CCX_Project_Manager__c> pmrec =[select CCX_Project__c,CCX_User_Account__c,Name from CCX_Project_Manager__c];     
         /*system.debug(pmrec);
        for(CCX_Project_Manager__c pmrec1:pmrec)
        {
            system.debug('project:'+pmrec1.CCX_Project__c);
        system.debug('user account :'+pmrec1.CCX_User_Account__c);
        system.debug('name:'+pmrec1.Name);
        }*/
       
        return pmrec;
       
    }
    

}